package it.amedeo.mybatis.javamodel;

public class Infcomuninew {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column infcomuninew.codregione
	 * @mbggenerated
	 */
	private String codregione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column infcomuninew.codiceprovincia
	 * @mbggenerated
	 */
	private String codiceprovincia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column infcomuninew.codicecomune
	 * @mbggenerated
	 */
	private String codicecomune;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column infcomuninew.codistat
	 * @mbggenerated
	 */
	private String codistat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column infcomuninew.siglaprovincia
	 * @mbggenerated
	 */
	private String siglaprovincia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column infcomuninew.infcodicecomune
	 * @mbggenerated
	 */
	private String infcodicecomune;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column infcomuninew.denomcomune
	 * @mbggenerated
	 */
	private String denomcomune;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column infcomuninew.denomregione
	 * @mbggenerated
	 */
	private String denomregione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column infcomuninew.codregione
	 * @return  the value of infcomuninew.codregione
	 * @mbggenerated
	 */
	public String getCodregione() {
		return codregione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column infcomuninew.codregione
	 * @param codregione  the value for infcomuninew.codregione
	 * @mbggenerated
	 */
	public void setCodregione(String codregione) {
		this.codregione = codregione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column infcomuninew.codiceprovincia
	 * @return  the value of infcomuninew.codiceprovincia
	 * @mbggenerated
	 */
	public String getCodiceprovincia() {
		return codiceprovincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column infcomuninew.codiceprovincia
	 * @param codiceprovincia  the value for infcomuninew.codiceprovincia
	 * @mbggenerated
	 */
	public void setCodiceprovincia(String codiceprovincia) {
		this.codiceprovincia = codiceprovincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column infcomuninew.codicecomune
	 * @return  the value of infcomuninew.codicecomune
	 * @mbggenerated
	 */
	public String getCodicecomune() {
		return codicecomune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column infcomuninew.codicecomune
	 * @param codicecomune  the value for infcomuninew.codicecomune
	 * @mbggenerated
	 */
	public void setCodicecomune(String codicecomune) {
		this.codicecomune = codicecomune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column infcomuninew.codistat
	 * @return  the value of infcomuninew.codistat
	 * @mbggenerated
	 */
	public String getCodistat() {
		return codistat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column infcomuninew.codistat
	 * @param codistat  the value for infcomuninew.codistat
	 * @mbggenerated
	 */
	public void setCodistat(String codistat) {
		this.codistat = codistat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column infcomuninew.siglaprovincia
	 * @return  the value of infcomuninew.siglaprovincia
	 * @mbggenerated
	 */
	public String getSiglaprovincia() {
		return siglaprovincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column infcomuninew.siglaprovincia
	 * @param siglaprovincia  the value for infcomuninew.siglaprovincia
	 * @mbggenerated
	 */
	public void setSiglaprovincia(String siglaprovincia) {
		this.siglaprovincia = siglaprovincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column infcomuninew.infcodicecomune
	 * @return  the value of infcomuninew.infcodicecomune
	 * @mbggenerated
	 */
	public String getInfcodicecomune() {
		return infcodicecomune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column infcomuninew.infcodicecomune
	 * @param infcodicecomune  the value for infcomuninew.infcodicecomune
	 * @mbggenerated
	 */
	public void setInfcodicecomune(String infcodicecomune) {
		this.infcodicecomune = infcodicecomune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column infcomuninew.denomcomune
	 * @return  the value of infcomuninew.denomcomune
	 * @mbggenerated
	 */
	public String getDenomcomune() {
		return denomcomune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column infcomuninew.denomcomune
	 * @param denomcomune  the value for infcomuninew.denomcomune
	 * @mbggenerated
	 */
	public void setDenomcomune(String denomcomune) {
		this.denomcomune = denomcomune;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column infcomuninew.denomregione
	 * @return  the value of infcomuninew.denomregione
	 * @mbggenerated
	 */
	public String getDenomregione() {
		return denomregione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column infcomuninew.denomregione
	 * @param denomregione  the value for infcomuninew.denomregione
	 * @mbggenerated
	 */
	public void setDenomregione(String denomregione) {
		this.denomregione = denomregione;
	}
}