package it.amedeo.mybatis.javamodel;

public class Regprv {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.CodiceRipartizione
	 * @mbggenerated
	 */
	private String codiceripartizione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.CodiceNUTS12006
	 * @mbggenerated
	 */
	private String codicenuts12006;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.CodiceNUTS12010
	 * @mbggenerated
	 */
	private String codicenuts12010;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.RipartizioneGeoMaiusc
	 * @mbggenerated
	 */
	private String ripartizionegeomaiusc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.RipartizioneGeo
	 * @mbggenerated
	 */
	private String ripartizionegeo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.CodiceRegione
	 * @mbggenerated
	 */
	private Integer codiceregione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.CodiceNUTS22006
	 * @mbggenerated
	 */
	private String codicenuts22006;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.CodiceNUTS22010
	 * @mbggenerated
	 */
	private String codicenuts22010;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.DenomRegioneMaiusc
	 * @mbggenerated
	 */
	private String denomregionemaiusc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.DenomRegione
	 * @mbggenerated
	 */
	private String denomregione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.CodProvincia
	 * @mbggenerated
	 */
	private Integer codprovincia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.CodiceNUTS32006
	 * @mbggenerated
	 */
	private String codicenuts32006;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.CodiceNUTS32010
	 * @mbggenerated
	 */
	private String codicenuts32010;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.DenomProvincia
	 * @mbggenerated
	 */
	private String denomprovincia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regprv.SiglaProvincia
	 * @mbggenerated
	 */
	private String siglaprovincia;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.CodiceRipartizione
	 * @return  the value of regprv.CodiceRipartizione
	 * @mbggenerated
	 */
	public String getCodiceripartizione() {
		return codiceripartizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.CodiceRipartizione
	 * @param codiceripartizione  the value for regprv.CodiceRipartizione
	 * @mbggenerated
	 */
	public void setCodiceripartizione(String codiceripartizione) {
		this.codiceripartizione = codiceripartizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.CodiceNUTS12006
	 * @return  the value of regprv.CodiceNUTS12006
	 * @mbggenerated
	 */
	public String getCodicenuts12006() {
		return codicenuts12006;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.CodiceNUTS12006
	 * @param codicenuts12006  the value for regprv.CodiceNUTS12006
	 * @mbggenerated
	 */
	public void setCodicenuts12006(String codicenuts12006) {
		this.codicenuts12006 = codicenuts12006;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.CodiceNUTS12010
	 * @return  the value of regprv.CodiceNUTS12010
	 * @mbggenerated
	 */
	public String getCodicenuts12010() {
		return codicenuts12010;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.CodiceNUTS12010
	 * @param codicenuts12010  the value for regprv.CodiceNUTS12010
	 * @mbggenerated
	 */
	public void setCodicenuts12010(String codicenuts12010) {
		this.codicenuts12010 = codicenuts12010;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.RipartizioneGeoMaiusc
	 * @return  the value of regprv.RipartizioneGeoMaiusc
	 * @mbggenerated
	 */
	public String getRipartizionegeomaiusc() {
		return ripartizionegeomaiusc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.RipartizioneGeoMaiusc
	 * @param ripartizionegeomaiusc  the value for regprv.RipartizioneGeoMaiusc
	 * @mbggenerated
	 */
	public void setRipartizionegeomaiusc(String ripartizionegeomaiusc) {
		this.ripartizionegeomaiusc = ripartizionegeomaiusc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.RipartizioneGeo
	 * @return  the value of regprv.RipartizioneGeo
	 * @mbggenerated
	 */
	public String getRipartizionegeo() {
		return ripartizionegeo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.RipartizioneGeo
	 * @param ripartizionegeo  the value for regprv.RipartizioneGeo
	 * @mbggenerated
	 */
	public void setRipartizionegeo(String ripartizionegeo) {
		this.ripartizionegeo = ripartizionegeo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.CodiceRegione
	 * @return  the value of regprv.CodiceRegione
	 * @mbggenerated
	 */
	public Integer getCodiceregione() {
		return codiceregione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.CodiceRegione
	 * @param codiceregione  the value for regprv.CodiceRegione
	 * @mbggenerated
	 */
	public void setCodiceregione(Integer codiceregione) {
		this.codiceregione = codiceregione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.CodiceNUTS22006
	 * @return  the value of regprv.CodiceNUTS22006
	 * @mbggenerated
	 */
	public String getCodicenuts22006() {
		return codicenuts22006;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.CodiceNUTS22006
	 * @param codicenuts22006  the value for regprv.CodiceNUTS22006
	 * @mbggenerated
	 */
	public void setCodicenuts22006(String codicenuts22006) {
		this.codicenuts22006 = codicenuts22006;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.CodiceNUTS22010
	 * @return  the value of regprv.CodiceNUTS22010
	 * @mbggenerated
	 */
	public String getCodicenuts22010() {
		return codicenuts22010;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.CodiceNUTS22010
	 * @param codicenuts22010  the value for regprv.CodiceNUTS22010
	 * @mbggenerated
	 */
	public void setCodicenuts22010(String codicenuts22010) {
		this.codicenuts22010 = codicenuts22010;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.DenomRegioneMaiusc
	 * @return  the value of regprv.DenomRegioneMaiusc
	 * @mbggenerated
	 */
	public String getDenomregionemaiusc() {
		return denomregionemaiusc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.DenomRegioneMaiusc
	 * @param denomregionemaiusc  the value for regprv.DenomRegioneMaiusc
	 * @mbggenerated
	 */
	public void setDenomregionemaiusc(String denomregionemaiusc) {
		this.denomregionemaiusc = denomregionemaiusc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.DenomRegione
	 * @return  the value of regprv.DenomRegione
	 * @mbggenerated
	 */
	public String getDenomregione() {
		return denomregione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.DenomRegione
	 * @param denomregione  the value for regprv.DenomRegione
	 * @mbggenerated
	 */
	public void setDenomregione(String denomregione) {
		this.denomregione = denomregione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.CodProvincia
	 * @return  the value of regprv.CodProvincia
	 * @mbggenerated
	 */
	public Integer getCodprovincia() {
		return codprovincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.CodProvincia
	 * @param codprovincia  the value for regprv.CodProvincia
	 * @mbggenerated
	 */
	public void setCodprovincia(Integer codprovincia) {
		this.codprovincia = codprovincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.CodiceNUTS32006
	 * @return  the value of regprv.CodiceNUTS32006
	 * @mbggenerated
	 */
	public String getCodicenuts32006() {
		return codicenuts32006;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.CodiceNUTS32006
	 * @param codicenuts32006  the value for regprv.CodiceNUTS32006
	 * @mbggenerated
	 */
	public void setCodicenuts32006(String codicenuts32006) {
		this.codicenuts32006 = codicenuts32006;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.CodiceNUTS32010
	 * @return  the value of regprv.CodiceNUTS32010
	 * @mbggenerated
	 */
	public String getCodicenuts32010() {
		return codicenuts32010;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.CodiceNUTS32010
	 * @param codicenuts32010  the value for regprv.CodiceNUTS32010
	 * @mbggenerated
	 */
	public void setCodicenuts32010(String codicenuts32010) {
		this.codicenuts32010 = codicenuts32010;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.DenomProvincia
	 * @return  the value of regprv.DenomProvincia
	 * @mbggenerated
	 */
	public String getDenomprovincia() {
		return denomprovincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.DenomProvincia
	 * @param denomprovincia  the value for regprv.DenomProvincia
	 * @mbggenerated
	 */
	public void setDenomprovincia(String denomprovincia) {
		this.denomprovincia = denomprovincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regprv.SiglaProvincia
	 * @return  the value of regprv.SiglaProvincia
	 * @mbggenerated
	 */
	public String getSiglaprovincia() {
		return siglaprovincia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regprv.SiglaProvincia
	 * @param siglaprovincia  the value for regprv.SiglaProvincia
	 * @mbggenerated
	 */
	public void setSiglaprovincia(String siglaprovincia) {
		this.siglaprovincia = siglaprovincia;
	}
}