package it.amedeo.mybatis.javamodel;

import java.util.ArrayList;
import java.util.List;

public class RegprvExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table regprv
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table regprv
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table regprv
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	public RegprvExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table regprv
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodiceripartizioneIsNull() {
			addCriterion("CodiceRipartizione is null");
			return (Criteria) this;
		}

		public Criteria andCodiceripartizioneIsNotNull() {
			addCriterion("CodiceRipartizione is not null");
			return (Criteria) this;
		}

		public Criteria andCodiceripartizioneEqualTo(String value) {
			addCriterion("CodiceRipartizione =", value, "codiceripartizione");
			return (Criteria) this;
		}

		public Criteria andCodiceripartizioneNotEqualTo(String value) {
			addCriterion("CodiceRipartizione <>", value, "codiceripartizione");
			return (Criteria) this;
		}

		public Criteria andCodiceripartizioneGreaterThan(String value) {
			addCriterion("CodiceRipartizione >", value, "codiceripartizione");
			return (Criteria) this;
		}

		public Criteria andCodiceripartizioneGreaterThanOrEqualTo(String value) {
			addCriterion("CodiceRipartizione >=", value, "codiceripartizione");
			return (Criteria) this;
		}

		public Criteria andCodiceripartizioneLessThan(String value) {
			addCriterion("CodiceRipartizione <", value, "codiceripartizione");
			return (Criteria) this;
		}

		public Criteria andCodiceripartizioneLessThanOrEqualTo(String value) {
			addCriterion("CodiceRipartizione <=", value, "codiceripartizione");
			return (Criteria) this;
		}

		public Criteria andCodiceripartizioneLike(String value) {
			addCriterion("CodiceRipartizione like", value, "codiceripartizione");
			return (Criteria) this;
		}

		public Criteria andCodiceripartizioneNotLike(String value) {
			addCriterion("CodiceRipartizione not like", value, "codiceripartizione");
			return (Criteria) this;
		}

		public Criteria andCodiceripartizioneIn(List<String> values) {
			addCriterion("CodiceRipartizione in", values, "codiceripartizione");
			return (Criteria) this;
		}

		public Criteria andCodiceripartizioneNotIn(List<String> values) {
			addCriterion("CodiceRipartizione not in", values, "codiceripartizione");
			return (Criteria) this;
		}

		public Criteria andCodiceripartizioneBetween(String value1, String value2) {
			addCriterion("CodiceRipartizione between", value1, value2, "codiceripartizione");
			return (Criteria) this;
		}

		public Criteria andCodiceripartizioneNotBetween(String value1, String value2) {
			addCriterion("CodiceRipartizione not between", value1, value2, "codiceripartizione");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006IsNull() {
			addCriterion("CodiceNUTS12006 is null");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006IsNotNull() {
			addCriterion("CodiceNUTS12006 is not null");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006EqualTo(String value) {
			addCriterion("CodiceNUTS12006 =", value, "codicenuts12006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006NotEqualTo(String value) {
			addCriterion("CodiceNUTS12006 <>", value, "codicenuts12006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006GreaterThan(String value) {
			addCriterion("CodiceNUTS12006 >", value, "codicenuts12006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006GreaterThanOrEqualTo(String value) {
			addCriterion("CodiceNUTS12006 >=", value, "codicenuts12006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006LessThan(String value) {
			addCriterion("CodiceNUTS12006 <", value, "codicenuts12006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006LessThanOrEqualTo(String value) {
			addCriterion("CodiceNUTS12006 <=", value, "codicenuts12006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006Like(String value) {
			addCriterion("CodiceNUTS12006 like", value, "codicenuts12006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006NotLike(String value) {
			addCriterion("CodiceNUTS12006 not like", value, "codicenuts12006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006In(List<String> values) {
			addCriterion("CodiceNUTS12006 in", values, "codicenuts12006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006NotIn(List<String> values) {
			addCriterion("CodiceNUTS12006 not in", values, "codicenuts12006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006Between(String value1, String value2) {
			addCriterion("CodiceNUTS12006 between", value1, value2, "codicenuts12006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12006NotBetween(String value1, String value2) {
			addCriterion("CodiceNUTS12006 not between", value1, value2, "codicenuts12006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010IsNull() {
			addCriterion("CodiceNUTS12010 is null");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010IsNotNull() {
			addCriterion("CodiceNUTS12010 is not null");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010EqualTo(String value) {
			addCriterion("CodiceNUTS12010 =", value, "codicenuts12010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010NotEqualTo(String value) {
			addCriterion("CodiceNUTS12010 <>", value, "codicenuts12010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010GreaterThan(String value) {
			addCriterion("CodiceNUTS12010 >", value, "codicenuts12010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010GreaterThanOrEqualTo(String value) {
			addCriterion("CodiceNUTS12010 >=", value, "codicenuts12010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010LessThan(String value) {
			addCriterion("CodiceNUTS12010 <", value, "codicenuts12010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010LessThanOrEqualTo(String value) {
			addCriterion("CodiceNUTS12010 <=", value, "codicenuts12010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010Like(String value) {
			addCriterion("CodiceNUTS12010 like", value, "codicenuts12010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010NotLike(String value) {
			addCriterion("CodiceNUTS12010 not like", value, "codicenuts12010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010In(List<String> values) {
			addCriterion("CodiceNUTS12010 in", values, "codicenuts12010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010NotIn(List<String> values) {
			addCriterion("CodiceNUTS12010 not in", values, "codicenuts12010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010Between(String value1, String value2) {
			addCriterion("CodiceNUTS12010 between", value1, value2, "codicenuts12010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts12010NotBetween(String value1, String value2) {
			addCriterion("CodiceNUTS12010 not between", value1, value2, "codicenuts12010");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscIsNull() {
			addCriterion("RipartizioneGeoMaiusc is null");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscIsNotNull() {
			addCriterion("RipartizioneGeoMaiusc is not null");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscEqualTo(String value) {
			addCriterion("RipartizioneGeoMaiusc =", value, "ripartizionegeomaiusc");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscNotEqualTo(String value) {
			addCriterion("RipartizioneGeoMaiusc <>", value, "ripartizionegeomaiusc");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscGreaterThan(String value) {
			addCriterion("RipartizioneGeoMaiusc >", value, "ripartizionegeomaiusc");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscGreaterThanOrEqualTo(String value) {
			addCriterion("RipartizioneGeoMaiusc >=", value, "ripartizionegeomaiusc");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscLessThan(String value) {
			addCriterion("RipartizioneGeoMaiusc <", value, "ripartizionegeomaiusc");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscLessThanOrEqualTo(String value) {
			addCriterion("RipartizioneGeoMaiusc <=", value, "ripartizionegeomaiusc");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscLike(String value) {
			addCriterion("RipartizioneGeoMaiusc like", value, "ripartizionegeomaiusc");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscNotLike(String value) {
			addCriterion("RipartizioneGeoMaiusc not like", value, "ripartizionegeomaiusc");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscIn(List<String> values) {
			addCriterion("RipartizioneGeoMaiusc in", values, "ripartizionegeomaiusc");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscNotIn(List<String> values) {
			addCriterion("RipartizioneGeoMaiusc not in", values, "ripartizionegeomaiusc");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscBetween(String value1, String value2) {
			addCriterion("RipartizioneGeoMaiusc between", value1, value2, "ripartizionegeomaiusc");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeomaiuscNotBetween(String value1, String value2) {
			addCriterion("RipartizioneGeoMaiusc not between", value1, value2, "ripartizionegeomaiusc");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoIsNull() {
			addCriterion("RipartizioneGeo is null");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoIsNotNull() {
			addCriterion("RipartizioneGeo is not null");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoEqualTo(String value) {
			addCriterion("RipartizioneGeo =", value, "ripartizionegeo");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoNotEqualTo(String value) {
			addCriterion("RipartizioneGeo <>", value, "ripartizionegeo");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoGreaterThan(String value) {
			addCriterion("RipartizioneGeo >", value, "ripartizionegeo");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoGreaterThanOrEqualTo(String value) {
			addCriterion("RipartizioneGeo >=", value, "ripartizionegeo");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoLessThan(String value) {
			addCriterion("RipartizioneGeo <", value, "ripartizionegeo");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoLessThanOrEqualTo(String value) {
			addCriterion("RipartizioneGeo <=", value, "ripartizionegeo");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoLike(String value) {
			addCriterion("RipartizioneGeo like", value, "ripartizionegeo");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoNotLike(String value) {
			addCriterion("RipartizioneGeo not like", value, "ripartizionegeo");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoIn(List<String> values) {
			addCriterion("RipartizioneGeo in", values, "ripartizionegeo");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoNotIn(List<String> values) {
			addCriterion("RipartizioneGeo not in", values, "ripartizionegeo");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoBetween(String value1, String value2) {
			addCriterion("RipartizioneGeo between", value1, value2, "ripartizionegeo");
			return (Criteria) this;
		}

		public Criteria andRipartizionegeoNotBetween(String value1, String value2) {
			addCriterion("RipartizioneGeo not between", value1, value2, "ripartizionegeo");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneIsNull() {
			addCriterion("CodiceRegione is null");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneIsNotNull() {
			addCriterion("CodiceRegione is not null");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneEqualTo(Integer value) {
			addCriterion("CodiceRegione =", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneNotEqualTo(Integer value) {
			addCriterion("CodiceRegione <>", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneGreaterThan(Integer value) {
			addCriterion("CodiceRegione >", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneGreaterThanOrEqualTo(Integer value) {
			addCriterion("CodiceRegione >=", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneLessThan(Integer value) {
			addCriterion("CodiceRegione <", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneLessThanOrEqualTo(Integer value) {
			addCriterion("CodiceRegione <=", value, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneIn(List<Integer> values) {
			addCriterion("CodiceRegione in", values, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneNotIn(List<Integer> values) {
			addCriterion("CodiceRegione not in", values, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneBetween(Integer value1, Integer value2) {
			addCriterion("CodiceRegione between", value1, value2, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodiceregioneNotBetween(Integer value1, Integer value2) {
			addCriterion("CodiceRegione not between", value1, value2, "codiceregione");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006IsNull() {
			addCriterion("CodiceNUTS22006 is null");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006IsNotNull() {
			addCriterion("CodiceNUTS22006 is not null");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006EqualTo(String value) {
			addCriterion("CodiceNUTS22006 =", value, "codicenuts22006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006NotEqualTo(String value) {
			addCriterion("CodiceNUTS22006 <>", value, "codicenuts22006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006GreaterThan(String value) {
			addCriterion("CodiceNUTS22006 >", value, "codicenuts22006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006GreaterThanOrEqualTo(String value) {
			addCriterion("CodiceNUTS22006 >=", value, "codicenuts22006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006LessThan(String value) {
			addCriterion("CodiceNUTS22006 <", value, "codicenuts22006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006LessThanOrEqualTo(String value) {
			addCriterion("CodiceNUTS22006 <=", value, "codicenuts22006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006Like(String value) {
			addCriterion("CodiceNUTS22006 like", value, "codicenuts22006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006NotLike(String value) {
			addCriterion("CodiceNUTS22006 not like", value, "codicenuts22006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006In(List<String> values) {
			addCriterion("CodiceNUTS22006 in", values, "codicenuts22006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006NotIn(List<String> values) {
			addCriterion("CodiceNUTS22006 not in", values, "codicenuts22006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006Between(String value1, String value2) {
			addCriterion("CodiceNUTS22006 between", value1, value2, "codicenuts22006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22006NotBetween(String value1, String value2) {
			addCriterion("CodiceNUTS22006 not between", value1, value2, "codicenuts22006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010IsNull() {
			addCriterion("CodiceNUTS22010 is null");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010IsNotNull() {
			addCriterion("CodiceNUTS22010 is not null");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010EqualTo(String value) {
			addCriterion("CodiceNUTS22010 =", value, "codicenuts22010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010NotEqualTo(String value) {
			addCriterion("CodiceNUTS22010 <>", value, "codicenuts22010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010GreaterThan(String value) {
			addCriterion("CodiceNUTS22010 >", value, "codicenuts22010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010GreaterThanOrEqualTo(String value) {
			addCriterion("CodiceNUTS22010 >=", value, "codicenuts22010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010LessThan(String value) {
			addCriterion("CodiceNUTS22010 <", value, "codicenuts22010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010LessThanOrEqualTo(String value) {
			addCriterion("CodiceNUTS22010 <=", value, "codicenuts22010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010Like(String value) {
			addCriterion("CodiceNUTS22010 like", value, "codicenuts22010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010NotLike(String value) {
			addCriterion("CodiceNUTS22010 not like", value, "codicenuts22010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010In(List<String> values) {
			addCriterion("CodiceNUTS22010 in", values, "codicenuts22010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010NotIn(List<String> values) {
			addCriterion("CodiceNUTS22010 not in", values, "codicenuts22010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010Between(String value1, String value2) {
			addCriterion("CodiceNUTS22010 between", value1, value2, "codicenuts22010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts22010NotBetween(String value1, String value2) {
			addCriterion("CodiceNUTS22010 not between", value1, value2, "codicenuts22010");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscIsNull() {
			addCriterion("DenomRegioneMaiusc is null");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscIsNotNull() {
			addCriterion("DenomRegioneMaiusc is not null");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscEqualTo(String value) {
			addCriterion("DenomRegioneMaiusc =", value, "denomregionemaiusc");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscNotEqualTo(String value) {
			addCriterion("DenomRegioneMaiusc <>", value, "denomregionemaiusc");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscGreaterThan(String value) {
			addCriterion("DenomRegioneMaiusc >", value, "denomregionemaiusc");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscGreaterThanOrEqualTo(String value) {
			addCriterion("DenomRegioneMaiusc >=", value, "denomregionemaiusc");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscLessThan(String value) {
			addCriterion("DenomRegioneMaiusc <", value, "denomregionemaiusc");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscLessThanOrEqualTo(String value) {
			addCriterion("DenomRegioneMaiusc <=", value, "denomregionemaiusc");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscLike(String value) {
			addCriterion("DenomRegioneMaiusc like", value, "denomregionemaiusc");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscNotLike(String value) {
			addCriterion("DenomRegioneMaiusc not like", value, "denomregionemaiusc");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscIn(List<String> values) {
			addCriterion("DenomRegioneMaiusc in", values, "denomregionemaiusc");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscNotIn(List<String> values) {
			addCriterion("DenomRegioneMaiusc not in", values, "denomregionemaiusc");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscBetween(String value1, String value2) {
			addCriterion("DenomRegioneMaiusc between", value1, value2, "denomregionemaiusc");
			return (Criteria) this;
		}

		public Criteria andDenomregionemaiuscNotBetween(String value1, String value2) {
			addCriterion("DenomRegioneMaiusc not between", value1, value2, "denomregionemaiusc");
			return (Criteria) this;
		}

		public Criteria andDenomregioneIsNull() {
			addCriterion("DenomRegione is null");
			return (Criteria) this;
		}

		public Criteria andDenomregioneIsNotNull() {
			addCriterion("DenomRegione is not null");
			return (Criteria) this;
		}

		public Criteria andDenomregioneEqualTo(String value) {
			addCriterion("DenomRegione =", value, "denomregione");
			return (Criteria) this;
		}

		public Criteria andDenomregioneNotEqualTo(String value) {
			addCriterion("DenomRegione <>", value, "denomregione");
			return (Criteria) this;
		}

		public Criteria andDenomregioneGreaterThan(String value) {
			addCriterion("DenomRegione >", value, "denomregione");
			return (Criteria) this;
		}

		public Criteria andDenomregioneGreaterThanOrEqualTo(String value) {
			addCriterion("DenomRegione >=", value, "denomregione");
			return (Criteria) this;
		}

		public Criteria andDenomregioneLessThan(String value) {
			addCriterion("DenomRegione <", value, "denomregione");
			return (Criteria) this;
		}

		public Criteria andDenomregioneLessThanOrEqualTo(String value) {
			addCriterion("DenomRegione <=", value, "denomregione");
			return (Criteria) this;
		}

		public Criteria andDenomregioneLike(String value) {
			addCriterion("DenomRegione like", value, "denomregione");
			return (Criteria) this;
		}

		public Criteria andDenomregioneNotLike(String value) {
			addCriterion("DenomRegione not like", value, "denomregione");
			return (Criteria) this;
		}

		public Criteria andDenomregioneIn(List<String> values) {
			addCriterion("DenomRegione in", values, "denomregione");
			return (Criteria) this;
		}

		public Criteria andDenomregioneNotIn(List<String> values) {
			addCriterion("DenomRegione not in", values, "denomregione");
			return (Criteria) this;
		}

		public Criteria andDenomregioneBetween(String value1, String value2) {
			addCriterion("DenomRegione between", value1, value2, "denomregione");
			return (Criteria) this;
		}

		public Criteria andDenomregioneNotBetween(String value1, String value2) {
			addCriterion("DenomRegione not between", value1, value2, "denomregione");
			return (Criteria) this;
		}

		public Criteria andCodprovinciaIsNull() {
			addCriterion("CodProvincia is null");
			return (Criteria) this;
		}

		public Criteria andCodprovinciaIsNotNull() {
			addCriterion("CodProvincia is not null");
			return (Criteria) this;
		}

		public Criteria andCodprovinciaEqualTo(Integer value) {
			addCriterion("CodProvincia =", value, "codprovincia");
			return (Criteria) this;
		}

		public Criteria andCodprovinciaNotEqualTo(Integer value) {
			addCriterion("CodProvincia <>", value, "codprovincia");
			return (Criteria) this;
		}

		public Criteria andCodprovinciaGreaterThan(Integer value) {
			addCriterion("CodProvincia >", value, "codprovincia");
			return (Criteria) this;
		}

		public Criteria andCodprovinciaGreaterThanOrEqualTo(Integer value) {
			addCriterion("CodProvincia >=", value, "codprovincia");
			return (Criteria) this;
		}

		public Criteria andCodprovinciaLessThan(Integer value) {
			addCriterion("CodProvincia <", value, "codprovincia");
			return (Criteria) this;
		}

		public Criteria andCodprovinciaLessThanOrEqualTo(Integer value) {
			addCriterion("CodProvincia <=", value, "codprovincia");
			return (Criteria) this;
		}

		public Criteria andCodprovinciaIn(List<Integer> values) {
			addCriterion("CodProvincia in", values, "codprovincia");
			return (Criteria) this;
		}

		public Criteria andCodprovinciaNotIn(List<Integer> values) {
			addCriterion("CodProvincia not in", values, "codprovincia");
			return (Criteria) this;
		}

		public Criteria andCodprovinciaBetween(Integer value1, Integer value2) {
			addCriterion("CodProvincia between", value1, value2, "codprovincia");
			return (Criteria) this;
		}

		public Criteria andCodprovinciaNotBetween(Integer value1, Integer value2) {
			addCriterion("CodProvincia not between", value1, value2, "codprovincia");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006IsNull() {
			addCriterion("CodiceNUTS32006 is null");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006IsNotNull() {
			addCriterion("CodiceNUTS32006 is not null");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006EqualTo(String value) {
			addCriterion("CodiceNUTS32006 =", value, "codicenuts32006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006NotEqualTo(String value) {
			addCriterion("CodiceNUTS32006 <>", value, "codicenuts32006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006GreaterThan(String value) {
			addCriterion("CodiceNUTS32006 >", value, "codicenuts32006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006GreaterThanOrEqualTo(String value) {
			addCriterion("CodiceNUTS32006 >=", value, "codicenuts32006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006LessThan(String value) {
			addCriterion("CodiceNUTS32006 <", value, "codicenuts32006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006LessThanOrEqualTo(String value) {
			addCriterion("CodiceNUTS32006 <=", value, "codicenuts32006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006Like(String value) {
			addCriterion("CodiceNUTS32006 like", value, "codicenuts32006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006NotLike(String value) {
			addCriterion("CodiceNUTS32006 not like", value, "codicenuts32006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006In(List<String> values) {
			addCriterion("CodiceNUTS32006 in", values, "codicenuts32006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006NotIn(List<String> values) {
			addCriterion("CodiceNUTS32006 not in", values, "codicenuts32006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006Between(String value1, String value2) {
			addCriterion("CodiceNUTS32006 between", value1, value2, "codicenuts32006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32006NotBetween(String value1, String value2) {
			addCriterion("CodiceNUTS32006 not between", value1, value2, "codicenuts32006");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010IsNull() {
			addCriterion("CodiceNUTS32010 is null");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010IsNotNull() {
			addCriterion("CodiceNUTS32010 is not null");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010EqualTo(String value) {
			addCriterion("CodiceNUTS32010 =", value, "codicenuts32010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010NotEqualTo(String value) {
			addCriterion("CodiceNUTS32010 <>", value, "codicenuts32010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010GreaterThan(String value) {
			addCriterion("CodiceNUTS32010 >", value, "codicenuts32010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010GreaterThanOrEqualTo(String value) {
			addCriterion("CodiceNUTS32010 >=", value, "codicenuts32010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010LessThan(String value) {
			addCriterion("CodiceNUTS32010 <", value, "codicenuts32010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010LessThanOrEqualTo(String value) {
			addCriterion("CodiceNUTS32010 <=", value, "codicenuts32010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010Like(String value) {
			addCriterion("CodiceNUTS32010 like", value, "codicenuts32010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010NotLike(String value) {
			addCriterion("CodiceNUTS32010 not like", value, "codicenuts32010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010In(List<String> values) {
			addCriterion("CodiceNUTS32010 in", values, "codicenuts32010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010NotIn(List<String> values) {
			addCriterion("CodiceNUTS32010 not in", values, "codicenuts32010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010Between(String value1, String value2) {
			addCriterion("CodiceNUTS32010 between", value1, value2, "codicenuts32010");
			return (Criteria) this;
		}

		public Criteria andCodicenuts32010NotBetween(String value1, String value2) {
			addCriterion("CodiceNUTS32010 not between", value1, value2, "codicenuts32010");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaIsNull() {
			addCriterion("DenomProvincia is null");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaIsNotNull() {
			addCriterion("DenomProvincia is not null");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaEqualTo(String value) {
			addCriterion("DenomProvincia =", value, "denomprovincia");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaNotEqualTo(String value) {
			addCriterion("DenomProvincia <>", value, "denomprovincia");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaGreaterThan(String value) {
			addCriterion("DenomProvincia >", value, "denomprovincia");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaGreaterThanOrEqualTo(String value) {
			addCriterion("DenomProvincia >=", value, "denomprovincia");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaLessThan(String value) {
			addCriterion("DenomProvincia <", value, "denomprovincia");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaLessThanOrEqualTo(String value) {
			addCriterion("DenomProvincia <=", value, "denomprovincia");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaLike(String value) {
			addCriterion("DenomProvincia like", value, "denomprovincia");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaNotLike(String value) {
			addCriterion("DenomProvincia not like", value, "denomprovincia");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaIn(List<String> values) {
			addCriterion("DenomProvincia in", values, "denomprovincia");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaNotIn(List<String> values) {
			addCriterion("DenomProvincia not in", values, "denomprovincia");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaBetween(String value1, String value2) {
			addCriterion("DenomProvincia between", value1, value2, "denomprovincia");
			return (Criteria) this;
		}

		public Criteria andDenomprovinciaNotBetween(String value1, String value2) {
			addCriterion("DenomProvincia not between", value1, value2, "denomprovincia");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaIsNull() {
			addCriterion("SiglaProvincia is null");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaIsNotNull() {
			addCriterion("SiglaProvincia is not null");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaEqualTo(String value) {
			addCriterion("SiglaProvincia =", value, "siglaprovincia");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaNotEqualTo(String value) {
			addCriterion("SiglaProvincia <>", value, "siglaprovincia");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaGreaterThan(String value) {
			addCriterion("SiglaProvincia >", value, "siglaprovincia");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaGreaterThanOrEqualTo(String value) {
			addCriterion("SiglaProvincia >=", value, "siglaprovincia");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaLessThan(String value) {
			addCriterion("SiglaProvincia <", value, "siglaprovincia");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaLessThanOrEqualTo(String value) {
			addCriterion("SiglaProvincia <=", value, "siglaprovincia");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaLike(String value) {
			addCriterion("SiglaProvincia like", value, "siglaprovincia");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaNotLike(String value) {
			addCriterion("SiglaProvincia not like", value, "siglaprovincia");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaIn(List<String> values) {
			addCriterion("SiglaProvincia in", values, "siglaprovincia");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaNotIn(List<String> values) {
			addCriterion("SiglaProvincia not in", values, "siglaprovincia");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaBetween(String value1, String value2) {
			addCriterion("SiglaProvincia between", value1, value2, "siglaprovincia");
			return (Criteria) this;
		}

		public Criteria andSiglaprovinciaNotBetween(String value1, String value2) {
			addCriterion("SiglaProvincia not between", value1, value2, "siglaprovincia");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table regprv
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table regprv
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 01 09:50:57 CET 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}