package it.amedeo.mybatis.javamodel;

public class Sarap {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarap.flgcan
	 * @mbggenerated
	 */
	private String flgcan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarap.kanagra
	 * @mbggenerated
	 */
	private String kanagra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarap.prgrec
	 * @mbggenerated
	 */
	private String prgrec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarap.lenpro
	 * @mbggenerated
	 */
	private String lenpro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarap.rigapro
	 * @mbggenerated
	 */
	private String rigapro;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarap.flgcan
	 * @return  the value of sarap.flgcan
	 * @mbggenerated
	 */
	public String getFlgcan() {
		return flgcan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarap.flgcan
	 * @param flgcan  the value for sarap.flgcan
	 * @mbggenerated
	 */
	public void setFlgcan(String flgcan) {
		this.flgcan = flgcan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarap.kanagra
	 * @return  the value of sarap.kanagra
	 * @mbggenerated
	 */
	public String getKanagra() {
		return kanagra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarap.kanagra
	 * @param kanagra  the value for sarap.kanagra
	 * @mbggenerated
	 */
	public void setKanagra(String kanagra) {
		this.kanagra = kanagra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarap.prgrec
	 * @return  the value of sarap.prgrec
	 * @mbggenerated
	 */
	public String getPrgrec() {
		return prgrec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarap.prgrec
	 * @param prgrec  the value for sarap.prgrec
	 * @mbggenerated
	 */
	public void setPrgrec(String prgrec) {
		this.prgrec = prgrec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarap.lenpro
	 * @return  the value of sarap.lenpro
	 * @mbggenerated
	 */
	public String getLenpro() {
		return lenpro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarap.lenpro
	 * @param lenpro  the value for sarap.lenpro
	 * @mbggenerated
	 */
	public void setLenpro(String lenpro) {
		this.lenpro = lenpro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarap.rigapro
	 * @return  the value of sarap.rigapro
	 * @mbggenerated
	 */
	public String getRigapro() {
		return rigapro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarap.rigapro
	 * @param rigapro  the value for sarap.rigapro
	 * @mbggenerated
	 */
	public void setRigapro(String rigapro) {
		this.rigapro = rigapro;
	}
}