package it.amedeo.mybatis.javamodel;

public class Saran {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.flgcan
	 * @mbggenerated
	 */
	private String flgcan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.k1saran
	 * @mbggenerated
	 */
	private String k1saran;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.kanagra
	 * @mbggenerated
	 */
	private String kanagra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.stares
	 * @mbggenerated
	 */
	private String stares;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.istres
	 * @mbggenerated
	 */
	private String istres;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.stanas
	 * @mbggenerated
	 */
	private String stanas;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.istnas
	 * @mbggenerated
	 */
	private String istnas;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.datnas
	 * @mbggenerated
	 */
	private String datnas;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.codfis
	 * @mbggenerated
	 */
	private String codfis;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.maxpro
	 * @mbggenerated
	 */
	private String maxpro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.timpro
	 * @mbggenerated
	 */
	private String timpro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.dtulpro
	 * @mbggenerated
	 */
	private String dtulpro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.datins
	 * @mbggenerated
	 */
	private String datins;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.lnomin
	 * @mbggenerated
	 */
	private String lnomin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column saran.nominat
	 * @mbggenerated
	 */
	private String nominat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.flgcan
	 * @return  the value of saran.flgcan
	 * @mbggenerated
	 */
	public String getFlgcan() {
		return flgcan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.flgcan
	 * @param flgcan  the value for saran.flgcan
	 * @mbggenerated
	 */
	public void setFlgcan(String flgcan) {
		this.flgcan = flgcan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.k1saran
	 * @return  the value of saran.k1saran
	 * @mbggenerated
	 */
	public String getK1saran() {
		return k1saran;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.k1saran
	 * @param k1saran  the value for saran.k1saran
	 * @mbggenerated
	 */
	public void setK1saran(String k1saran) {
		this.k1saran = k1saran;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.kanagra
	 * @return  the value of saran.kanagra
	 * @mbggenerated
	 */
	public String getKanagra() {
		return kanagra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.kanagra
	 * @param kanagra  the value for saran.kanagra
	 * @mbggenerated
	 */
	public void setKanagra(String kanagra) {
		this.kanagra = kanagra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.stares
	 * @return  the value of saran.stares
	 * @mbggenerated
	 */
	public String getStares() {
		return stares;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.stares
	 * @param stares  the value for saran.stares
	 * @mbggenerated
	 */
	public void setStares(String stares) {
		this.stares = stares;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.istres
	 * @return  the value of saran.istres
	 * @mbggenerated
	 */
	public String getIstres() {
		return istres;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.istres
	 * @param istres  the value for saran.istres
	 * @mbggenerated
	 */
	public void setIstres(String istres) {
		this.istres = istres;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.stanas
	 * @return  the value of saran.stanas
	 * @mbggenerated
	 */
	public String getStanas() {
		return stanas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.stanas
	 * @param stanas  the value for saran.stanas
	 * @mbggenerated
	 */
	public void setStanas(String stanas) {
		this.stanas = stanas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.istnas
	 * @return  the value of saran.istnas
	 * @mbggenerated
	 */
	public String getIstnas() {
		return istnas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.istnas
	 * @param istnas  the value for saran.istnas
	 * @mbggenerated
	 */
	public void setIstnas(String istnas) {
		this.istnas = istnas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.datnas
	 * @return  the value of saran.datnas
	 * @mbggenerated
	 */
	public String getDatnas() {
		return datnas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.datnas
	 * @param datnas  the value for saran.datnas
	 * @mbggenerated
	 */
	public void setDatnas(String datnas) {
		this.datnas = datnas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.codfis
	 * @return  the value of saran.codfis
	 * @mbggenerated
	 */
	public String getCodfis() {
		return codfis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.codfis
	 * @param codfis  the value for saran.codfis
	 * @mbggenerated
	 */
	public void setCodfis(String codfis) {
		this.codfis = codfis;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.maxpro
	 * @return  the value of saran.maxpro
	 * @mbggenerated
	 */
	public String getMaxpro() {
		return maxpro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.maxpro
	 * @param maxpro  the value for saran.maxpro
	 * @mbggenerated
	 */
	public void setMaxpro(String maxpro) {
		this.maxpro = maxpro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.timpro
	 * @return  the value of saran.timpro
	 * @mbggenerated
	 */
	public String getTimpro() {
		return timpro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.timpro
	 * @param timpro  the value for saran.timpro
	 * @mbggenerated
	 */
	public void setTimpro(String timpro) {
		this.timpro = timpro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.dtulpro
	 * @return  the value of saran.dtulpro
	 * @mbggenerated
	 */
	public String getDtulpro() {
		return dtulpro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.dtulpro
	 * @param dtulpro  the value for saran.dtulpro
	 * @mbggenerated
	 */
	public void setDtulpro(String dtulpro) {
		this.dtulpro = dtulpro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.datins
	 * @return  the value of saran.datins
	 * @mbggenerated
	 */
	public String getDatins() {
		return datins;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.datins
	 * @param datins  the value for saran.datins
	 * @mbggenerated
	 */
	public void setDatins(String datins) {
		this.datins = datins;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.lnomin
	 * @return  the value of saran.lnomin
	 * @mbggenerated
	 */
	public String getLnomin() {
		return lnomin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.lnomin
	 * @param lnomin  the value for saran.lnomin
	 * @mbggenerated
	 */
	public void setLnomin(String lnomin) {
		this.lnomin = lnomin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column saran.nominat
	 * @return  the value of saran.nominat
	 * @mbggenerated
	 */
	public String getNominat() {
		return nominat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column saran.nominat
	 * @param nominat  the value for saran.nominat
	 * @mbggenerated
	 */
	public void setNominat(String nominat) {
		this.nominat = nominat;
	}
}