package it.amedeo.mybatis.javamodel;

import java.util.ArrayList;
import java.util.List;

public class SarapExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sarap
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sarap
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sarap
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	public SarapExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sarap
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andFlgcanIsNull() {
			addCriterion("flgcan is null");
			return (Criteria) this;
		}

		public Criteria andFlgcanIsNotNull() {
			addCriterion("flgcan is not null");
			return (Criteria) this;
		}

		public Criteria andFlgcanEqualTo(String value) {
			addCriterion("flgcan =", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanNotEqualTo(String value) {
			addCriterion("flgcan <>", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanGreaterThan(String value) {
			addCriterion("flgcan >", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanGreaterThanOrEqualTo(String value) {
			addCriterion("flgcan >=", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanLessThan(String value) {
			addCriterion("flgcan <", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanLessThanOrEqualTo(String value) {
			addCriterion("flgcan <=", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanLike(String value) {
			addCriterion("flgcan like", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanNotLike(String value) {
			addCriterion("flgcan not like", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanIn(List<String> values) {
			addCriterion("flgcan in", values, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanNotIn(List<String> values) {
			addCriterion("flgcan not in", values, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanBetween(String value1, String value2) {
			addCriterion("flgcan between", value1, value2, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanNotBetween(String value1, String value2) {
			addCriterion("flgcan not between", value1, value2, "flgcan");
			return (Criteria) this;
		}

		public Criteria andKanagraIsNull() {
			addCriterion("kanagra is null");
			return (Criteria) this;
		}

		public Criteria andKanagraIsNotNull() {
			addCriterion("kanagra is not null");
			return (Criteria) this;
		}

		public Criteria andKanagraEqualTo(String value) {
			addCriterion("kanagra =", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraNotEqualTo(String value) {
			addCriterion("kanagra <>", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraGreaterThan(String value) {
			addCriterion("kanagra >", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraGreaterThanOrEqualTo(String value) {
			addCriterion("kanagra >=", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraLessThan(String value) {
			addCriterion("kanagra <", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraLessThanOrEqualTo(String value) {
			addCriterion("kanagra <=", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraLike(String value) {
			addCriterion("kanagra like", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraNotLike(String value) {
			addCriterion("kanagra not like", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraIn(List<String> values) {
			addCriterion("kanagra in", values, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraNotIn(List<String> values) {
			addCriterion("kanagra not in", values, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraBetween(String value1, String value2) {
			addCriterion("kanagra between", value1, value2, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraNotBetween(String value1, String value2) {
			addCriterion("kanagra not between", value1, value2, "kanagra");
			return (Criteria) this;
		}

		public Criteria andPrgrecIsNull() {
			addCriterion("prgrec is null");
			return (Criteria) this;
		}

		public Criteria andPrgrecIsNotNull() {
			addCriterion("prgrec is not null");
			return (Criteria) this;
		}

		public Criteria andPrgrecEqualTo(String value) {
			addCriterion("prgrec =", value, "prgrec");
			return (Criteria) this;
		}

		public Criteria andPrgrecNotEqualTo(String value) {
			addCriterion("prgrec <>", value, "prgrec");
			return (Criteria) this;
		}

		public Criteria andPrgrecGreaterThan(String value) {
			addCriterion("prgrec >", value, "prgrec");
			return (Criteria) this;
		}

		public Criteria andPrgrecGreaterThanOrEqualTo(String value) {
			addCriterion("prgrec >=", value, "prgrec");
			return (Criteria) this;
		}

		public Criteria andPrgrecLessThan(String value) {
			addCriterion("prgrec <", value, "prgrec");
			return (Criteria) this;
		}

		public Criteria andPrgrecLessThanOrEqualTo(String value) {
			addCriterion("prgrec <=", value, "prgrec");
			return (Criteria) this;
		}

		public Criteria andPrgrecLike(String value) {
			addCriterion("prgrec like", value, "prgrec");
			return (Criteria) this;
		}

		public Criteria andPrgrecNotLike(String value) {
			addCriterion("prgrec not like", value, "prgrec");
			return (Criteria) this;
		}

		public Criteria andPrgrecIn(List<String> values) {
			addCriterion("prgrec in", values, "prgrec");
			return (Criteria) this;
		}

		public Criteria andPrgrecNotIn(List<String> values) {
			addCriterion("prgrec not in", values, "prgrec");
			return (Criteria) this;
		}

		public Criteria andPrgrecBetween(String value1, String value2) {
			addCriterion("prgrec between", value1, value2, "prgrec");
			return (Criteria) this;
		}

		public Criteria andPrgrecNotBetween(String value1, String value2) {
			addCriterion("prgrec not between", value1, value2, "prgrec");
			return (Criteria) this;
		}

		public Criteria andLenproIsNull() {
			addCriterion("lenpro is null");
			return (Criteria) this;
		}

		public Criteria andLenproIsNotNull() {
			addCriterion("lenpro is not null");
			return (Criteria) this;
		}

		public Criteria andLenproEqualTo(String value) {
			addCriterion("lenpro =", value, "lenpro");
			return (Criteria) this;
		}

		public Criteria andLenproNotEqualTo(String value) {
			addCriterion("lenpro <>", value, "lenpro");
			return (Criteria) this;
		}

		public Criteria andLenproGreaterThan(String value) {
			addCriterion("lenpro >", value, "lenpro");
			return (Criteria) this;
		}

		public Criteria andLenproGreaterThanOrEqualTo(String value) {
			addCriterion("lenpro >=", value, "lenpro");
			return (Criteria) this;
		}

		public Criteria andLenproLessThan(String value) {
			addCriterion("lenpro <", value, "lenpro");
			return (Criteria) this;
		}

		public Criteria andLenproLessThanOrEqualTo(String value) {
			addCriterion("lenpro <=", value, "lenpro");
			return (Criteria) this;
		}

		public Criteria andLenproLike(String value) {
			addCriterion("lenpro like", value, "lenpro");
			return (Criteria) this;
		}

		public Criteria andLenproNotLike(String value) {
			addCriterion("lenpro not like", value, "lenpro");
			return (Criteria) this;
		}

		public Criteria andLenproIn(List<String> values) {
			addCriterion("lenpro in", values, "lenpro");
			return (Criteria) this;
		}

		public Criteria andLenproNotIn(List<String> values) {
			addCriterion("lenpro not in", values, "lenpro");
			return (Criteria) this;
		}

		public Criteria andLenproBetween(String value1, String value2) {
			addCriterion("lenpro between", value1, value2, "lenpro");
			return (Criteria) this;
		}

		public Criteria andLenproNotBetween(String value1, String value2) {
			addCriterion("lenpro not between", value1, value2, "lenpro");
			return (Criteria) this;
		}

		public Criteria andRigaproIsNull() {
			addCriterion("rigapro is null");
			return (Criteria) this;
		}

		public Criteria andRigaproIsNotNull() {
			addCriterion("rigapro is not null");
			return (Criteria) this;
		}

		public Criteria andRigaproEqualTo(String value) {
			addCriterion("rigapro =", value, "rigapro");
			return (Criteria) this;
		}

		public Criteria andRigaproNotEqualTo(String value) {
			addCriterion("rigapro <>", value, "rigapro");
			return (Criteria) this;
		}

		public Criteria andRigaproGreaterThan(String value) {
			addCriterion("rigapro >", value, "rigapro");
			return (Criteria) this;
		}

		public Criteria andRigaproGreaterThanOrEqualTo(String value) {
			addCriterion("rigapro >=", value, "rigapro");
			return (Criteria) this;
		}

		public Criteria andRigaproLessThan(String value) {
			addCriterion("rigapro <", value, "rigapro");
			return (Criteria) this;
		}

		public Criteria andRigaproLessThanOrEqualTo(String value) {
			addCriterion("rigapro <=", value, "rigapro");
			return (Criteria) this;
		}

		public Criteria andRigaproLike(String value) {
			addCriterion("rigapro like", value, "rigapro");
			return (Criteria) this;
		}

		public Criteria andRigaproNotLike(String value) {
			addCriterion("rigapro not like", value, "rigapro");
			return (Criteria) this;
		}

		public Criteria andRigaproIn(List<String> values) {
			addCriterion("rigapro in", values, "rigapro");
			return (Criteria) this;
		}

		public Criteria andRigaproNotIn(List<String> values) {
			addCriterion("rigapro not in", values, "rigapro");
			return (Criteria) this;
		}

		public Criteria andRigaproBetween(String value1, String value2) {
			addCriterion("rigapro between", value1, value2, "rigapro");
			return (Criteria) this;
		}

		public Criteria andRigaproNotBetween(String value1, String value2) {
			addCriterion("rigapro not between", value1, value2, "rigapro");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sarap
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sarap
     *
     * @mbggenerated do_not_delete_during_merge Mon Feb 18 16:23:50 CET 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}