package it.amedeo.mybatis.javamodel;

import java.util.ArrayList;
import java.util.List;

public class SaranExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table saran
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table saran
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table saran
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	public SaranExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table saran
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andFlgcanIsNull() {
			addCriterion("flgcan is null");
			return (Criteria) this;
		}

		public Criteria andFlgcanIsNotNull() {
			addCriterion("flgcan is not null");
			return (Criteria) this;
		}

		public Criteria andFlgcanEqualTo(String value) {
			addCriterion("flgcan =", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanNotEqualTo(String value) {
			addCriterion("flgcan <>", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanGreaterThan(String value) {
			addCriterion("flgcan >", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanGreaterThanOrEqualTo(String value) {
			addCriterion("flgcan >=", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanLessThan(String value) {
			addCriterion("flgcan <", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanLessThanOrEqualTo(String value) {
			addCriterion("flgcan <=", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanLike(String value) {
			addCriterion("flgcan like", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanNotLike(String value) {
			addCriterion("flgcan not like", value, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanIn(List<String> values) {
			addCriterion("flgcan in", values, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanNotIn(List<String> values) {
			addCriterion("flgcan not in", values, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanBetween(String value1, String value2) {
			addCriterion("flgcan between", value1, value2, "flgcan");
			return (Criteria) this;
		}

		public Criteria andFlgcanNotBetween(String value1, String value2) {
			addCriterion("flgcan not between", value1, value2, "flgcan");
			return (Criteria) this;
		}

		public Criteria andK1saranIsNull() {
			addCriterion("k1saran is null");
			return (Criteria) this;
		}

		public Criteria andK1saranIsNotNull() {
			addCriterion("k1saran is not null");
			return (Criteria) this;
		}

		public Criteria andK1saranEqualTo(String value) {
			addCriterion("k1saran =", value, "k1saran");
			return (Criteria) this;
		}

		public Criteria andK1saranNotEqualTo(String value) {
			addCriterion("k1saran <>", value, "k1saran");
			return (Criteria) this;
		}

		public Criteria andK1saranGreaterThan(String value) {
			addCriterion("k1saran >", value, "k1saran");
			return (Criteria) this;
		}

		public Criteria andK1saranGreaterThanOrEqualTo(String value) {
			addCriterion("k1saran >=", value, "k1saran");
			return (Criteria) this;
		}

		public Criteria andK1saranLessThan(String value) {
			addCriterion("k1saran <", value, "k1saran");
			return (Criteria) this;
		}

		public Criteria andK1saranLessThanOrEqualTo(String value) {
			addCriterion("k1saran <=", value, "k1saran");
			return (Criteria) this;
		}

		public Criteria andK1saranLike(String value) {
			addCriterion("k1saran like", value, "k1saran");
			return (Criteria) this;
		}

		public Criteria andK1saranNotLike(String value) {
			addCriterion("k1saran not like", value, "k1saran");
			return (Criteria) this;
		}

		public Criteria andK1saranIn(List<String> values) {
			addCriterion("k1saran in", values, "k1saran");
			return (Criteria) this;
		}

		public Criteria andK1saranNotIn(List<String> values) {
			addCriterion("k1saran not in", values, "k1saran");
			return (Criteria) this;
		}

		public Criteria andK1saranBetween(String value1, String value2) {
			addCriterion("k1saran between", value1, value2, "k1saran");
			return (Criteria) this;
		}

		public Criteria andK1saranNotBetween(String value1, String value2) {
			addCriterion("k1saran not between", value1, value2, "k1saran");
			return (Criteria) this;
		}

		public Criteria andKanagraIsNull() {
			addCriterion("kanagra is null");
			return (Criteria) this;
		}

		public Criteria andKanagraIsNotNull() {
			addCriterion("kanagra is not null");
			return (Criteria) this;
		}

		public Criteria andKanagraEqualTo(String value) {
			addCriterion("kanagra =", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraNotEqualTo(String value) {
			addCriterion("kanagra <>", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraGreaterThan(String value) {
			addCriterion("kanagra >", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraGreaterThanOrEqualTo(String value) {
			addCriterion("kanagra >=", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraLessThan(String value) {
			addCriterion("kanagra <", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraLessThanOrEqualTo(String value) {
			addCriterion("kanagra <=", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraLike(String value) {
			addCriterion("kanagra like", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraNotLike(String value) {
			addCriterion("kanagra not like", value, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraIn(List<String> values) {
			addCriterion("kanagra in", values, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraNotIn(List<String> values) {
			addCriterion("kanagra not in", values, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraBetween(String value1, String value2) {
			addCriterion("kanagra between", value1, value2, "kanagra");
			return (Criteria) this;
		}

		public Criteria andKanagraNotBetween(String value1, String value2) {
			addCriterion("kanagra not between", value1, value2, "kanagra");
			return (Criteria) this;
		}

		public Criteria andStaresIsNull() {
			addCriterion("stares is null");
			return (Criteria) this;
		}

		public Criteria andStaresIsNotNull() {
			addCriterion("stares is not null");
			return (Criteria) this;
		}

		public Criteria andStaresEqualTo(String value) {
			addCriterion("stares =", value, "stares");
			return (Criteria) this;
		}

		public Criteria andStaresNotEqualTo(String value) {
			addCriterion("stares <>", value, "stares");
			return (Criteria) this;
		}

		public Criteria andStaresGreaterThan(String value) {
			addCriterion("stares >", value, "stares");
			return (Criteria) this;
		}

		public Criteria andStaresGreaterThanOrEqualTo(String value) {
			addCriterion("stares >=", value, "stares");
			return (Criteria) this;
		}

		public Criteria andStaresLessThan(String value) {
			addCriterion("stares <", value, "stares");
			return (Criteria) this;
		}

		public Criteria andStaresLessThanOrEqualTo(String value) {
			addCriterion("stares <=", value, "stares");
			return (Criteria) this;
		}

		public Criteria andStaresLike(String value) {
			addCriterion("stares like", value, "stares");
			return (Criteria) this;
		}

		public Criteria andStaresNotLike(String value) {
			addCriterion("stares not like", value, "stares");
			return (Criteria) this;
		}

		public Criteria andStaresIn(List<String> values) {
			addCriterion("stares in", values, "stares");
			return (Criteria) this;
		}

		public Criteria andStaresNotIn(List<String> values) {
			addCriterion("stares not in", values, "stares");
			return (Criteria) this;
		}

		public Criteria andStaresBetween(String value1, String value2) {
			addCriterion("stares between", value1, value2, "stares");
			return (Criteria) this;
		}

		public Criteria andStaresNotBetween(String value1, String value2) {
			addCriterion("stares not between", value1, value2, "stares");
			return (Criteria) this;
		}

		public Criteria andIstresIsNull() {
			addCriterion("istres is null");
			return (Criteria) this;
		}

		public Criteria andIstresIsNotNull() {
			addCriterion("istres is not null");
			return (Criteria) this;
		}

		public Criteria andIstresEqualTo(String value) {
			addCriterion("istres =", value, "istres");
			return (Criteria) this;
		}

		public Criteria andIstresNotEqualTo(String value) {
			addCriterion("istres <>", value, "istres");
			return (Criteria) this;
		}

		public Criteria andIstresGreaterThan(String value) {
			addCriterion("istres >", value, "istres");
			return (Criteria) this;
		}

		public Criteria andIstresGreaterThanOrEqualTo(String value) {
			addCriterion("istres >=", value, "istres");
			return (Criteria) this;
		}

		public Criteria andIstresLessThan(String value) {
			addCriterion("istres <", value, "istres");
			return (Criteria) this;
		}

		public Criteria andIstresLessThanOrEqualTo(String value) {
			addCriterion("istres <=", value, "istres");
			return (Criteria) this;
		}

		public Criteria andIstresLike(String value) {
			addCriterion("istres like", value, "istres");
			return (Criteria) this;
		}

		public Criteria andIstresNotLike(String value) {
			addCriterion("istres not like", value, "istres");
			return (Criteria) this;
		}

		public Criteria andIstresIn(List<String> values) {
			addCriterion("istres in", values, "istres");
			return (Criteria) this;
		}

		public Criteria andIstresNotIn(List<String> values) {
			addCriterion("istres not in", values, "istres");
			return (Criteria) this;
		}

		public Criteria andIstresBetween(String value1, String value2) {
			addCriterion("istres between", value1, value2, "istres");
			return (Criteria) this;
		}

		public Criteria andIstresNotBetween(String value1, String value2) {
			addCriterion("istres not between", value1, value2, "istres");
			return (Criteria) this;
		}

		public Criteria andStanasIsNull() {
			addCriterion("stanas is null");
			return (Criteria) this;
		}

		public Criteria andStanasIsNotNull() {
			addCriterion("stanas is not null");
			return (Criteria) this;
		}

		public Criteria andStanasEqualTo(String value) {
			addCriterion("stanas =", value, "stanas");
			return (Criteria) this;
		}

		public Criteria andStanasNotEqualTo(String value) {
			addCriterion("stanas <>", value, "stanas");
			return (Criteria) this;
		}

		public Criteria andStanasGreaterThan(String value) {
			addCriterion("stanas >", value, "stanas");
			return (Criteria) this;
		}

		public Criteria andStanasGreaterThanOrEqualTo(String value) {
			addCriterion("stanas >=", value, "stanas");
			return (Criteria) this;
		}

		public Criteria andStanasLessThan(String value) {
			addCriterion("stanas <", value, "stanas");
			return (Criteria) this;
		}

		public Criteria andStanasLessThanOrEqualTo(String value) {
			addCriterion("stanas <=", value, "stanas");
			return (Criteria) this;
		}

		public Criteria andStanasLike(String value) {
			addCriterion("stanas like", value, "stanas");
			return (Criteria) this;
		}

		public Criteria andStanasNotLike(String value) {
			addCriterion("stanas not like", value, "stanas");
			return (Criteria) this;
		}

		public Criteria andStanasIn(List<String> values) {
			addCriterion("stanas in", values, "stanas");
			return (Criteria) this;
		}

		public Criteria andStanasNotIn(List<String> values) {
			addCriterion("stanas not in", values, "stanas");
			return (Criteria) this;
		}

		public Criteria andStanasBetween(String value1, String value2) {
			addCriterion("stanas between", value1, value2, "stanas");
			return (Criteria) this;
		}

		public Criteria andStanasNotBetween(String value1, String value2) {
			addCriterion("stanas not between", value1, value2, "stanas");
			return (Criteria) this;
		}

		public Criteria andIstnasIsNull() {
			addCriterion("istnas is null");
			return (Criteria) this;
		}

		public Criteria andIstnasIsNotNull() {
			addCriterion("istnas is not null");
			return (Criteria) this;
		}

		public Criteria andIstnasEqualTo(String value) {
			addCriterion("istnas =", value, "istnas");
			return (Criteria) this;
		}

		public Criteria andIstnasNotEqualTo(String value) {
			addCriterion("istnas <>", value, "istnas");
			return (Criteria) this;
		}

		public Criteria andIstnasGreaterThan(String value) {
			addCriterion("istnas >", value, "istnas");
			return (Criteria) this;
		}

		public Criteria andIstnasGreaterThanOrEqualTo(String value) {
			addCriterion("istnas >=", value, "istnas");
			return (Criteria) this;
		}

		public Criteria andIstnasLessThan(String value) {
			addCriterion("istnas <", value, "istnas");
			return (Criteria) this;
		}

		public Criteria andIstnasLessThanOrEqualTo(String value) {
			addCriterion("istnas <=", value, "istnas");
			return (Criteria) this;
		}

		public Criteria andIstnasLike(String value) {
			addCriterion("istnas like", value, "istnas");
			return (Criteria) this;
		}

		public Criteria andIstnasNotLike(String value) {
			addCriterion("istnas not like", value, "istnas");
			return (Criteria) this;
		}

		public Criteria andIstnasIn(List<String> values) {
			addCriterion("istnas in", values, "istnas");
			return (Criteria) this;
		}

		public Criteria andIstnasNotIn(List<String> values) {
			addCriterion("istnas not in", values, "istnas");
			return (Criteria) this;
		}

		public Criteria andIstnasBetween(String value1, String value2) {
			addCriterion("istnas between", value1, value2, "istnas");
			return (Criteria) this;
		}

		public Criteria andIstnasNotBetween(String value1, String value2) {
			addCriterion("istnas not between", value1, value2, "istnas");
			return (Criteria) this;
		}

		public Criteria andDatnasIsNull() {
			addCriterion("datnas is null");
			return (Criteria) this;
		}

		public Criteria andDatnasIsNotNull() {
			addCriterion("datnas is not null");
			return (Criteria) this;
		}

		public Criteria andDatnasEqualTo(String value) {
			addCriterion("datnas =", value, "datnas");
			return (Criteria) this;
		}

		public Criteria andDatnasNotEqualTo(String value) {
			addCriterion("datnas <>", value, "datnas");
			return (Criteria) this;
		}

		public Criteria andDatnasGreaterThan(String value) {
			addCriterion("datnas >", value, "datnas");
			return (Criteria) this;
		}

		public Criteria andDatnasGreaterThanOrEqualTo(String value) {
			addCriterion("datnas >=", value, "datnas");
			return (Criteria) this;
		}

		public Criteria andDatnasLessThan(String value) {
			addCriterion("datnas <", value, "datnas");
			return (Criteria) this;
		}

		public Criteria andDatnasLessThanOrEqualTo(String value) {
			addCriterion("datnas <=", value, "datnas");
			return (Criteria) this;
		}

		public Criteria andDatnasLike(String value) {
			addCriterion("datnas like", value, "datnas");
			return (Criteria) this;
		}

		public Criteria andDatnasNotLike(String value) {
			addCriterion("datnas not like", value, "datnas");
			return (Criteria) this;
		}

		public Criteria andDatnasIn(List<String> values) {
			addCriterion("datnas in", values, "datnas");
			return (Criteria) this;
		}

		public Criteria andDatnasNotIn(List<String> values) {
			addCriterion("datnas not in", values, "datnas");
			return (Criteria) this;
		}

		public Criteria andDatnasBetween(String value1, String value2) {
			addCriterion("datnas between", value1, value2, "datnas");
			return (Criteria) this;
		}

		public Criteria andDatnasNotBetween(String value1, String value2) {
			addCriterion("datnas not between", value1, value2, "datnas");
			return (Criteria) this;
		}

		public Criteria andCodfisIsNull() {
			addCriterion("codfis is null");
			return (Criteria) this;
		}

		public Criteria andCodfisIsNotNull() {
			addCriterion("codfis is not null");
			return (Criteria) this;
		}

		public Criteria andCodfisEqualTo(String value) {
			addCriterion("codfis =", value, "codfis");
			return (Criteria) this;
		}

		public Criteria andCodfisNotEqualTo(String value) {
			addCriterion("codfis <>", value, "codfis");
			return (Criteria) this;
		}

		public Criteria andCodfisGreaterThan(String value) {
			addCriterion("codfis >", value, "codfis");
			return (Criteria) this;
		}

		public Criteria andCodfisGreaterThanOrEqualTo(String value) {
			addCriterion("codfis >=", value, "codfis");
			return (Criteria) this;
		}

		public Criteria andCodfisLessThan(String value) {
			addCriterion("codfis <", value, "codfis");
			return (Criteria) this;
		}

		public Criteria andCodfisLessThanOrEqualTo(String value) {
			addCriterion("codfis <=", value, "codfis");
			return (Criteria) this;
		}

		public Criteria andCodfisLike(String value) {
			addCriterion("codfis like", value, "codfis");
			return (Criteria) this;
		}

		public Criteria andCodfisNotLike(String value) {
			addCriterion("codfis not like", value, "codfis");
			return (Criteria) this;
		}

		public Criteria andCodfisIn(List<String> values) {
			addCriterion("codfis in", values, "codfis");
			return (Criteria) this;
		}

		public Criteria andCodfisNotIn(List<String> values) {
			addCriterion("codfis not in", values, "codfis");
			return (Criteria) this;
		}

		public Criteria andCodfisBetween(String value1, String value2) {
			addCriterion("codfis between", value1, value2, "codfis");
			return (Criteria) this;
		}

		public Criteria andCodfisNotBetween(String value1, String value2) {
			addCriterion("codfis not between", value1, value2, "codfis");
			return (Criteria) this;
		}

		public Criteria andMaxproIsNull() {
			addCriterion("maxpro is null");
			return (Criteria) this;
		}

		public Criteria andMaxproIsNotNull() {
			addCriterion("maxpro is not null");
			return (Criteria) this;
		}

		public Criteria andMaxproEqualTo(String value) {
			addCriterion("maxpro =", value, "maxpro");
			return (Criteria) this;
		}

		public Criteria andMaxproNotEqualTo(String value) {
			addCriterion("maxpro <>", value, "maxpro");
			return (Criteria) this;
		}

		public Criteria andMaxproGreaterThan(String value) {
			addCriterion("maxpro >", value, "maxpro");
			return (Criteria) this;
		}

		public Criteria andMaxproGreaterThanOrEqualTo(String value) {
			addCriterion("maxpro >=", value, "maxpro");
			return (Criteria) this;
		}

		public Criteria andMaxproLessThan(String value) {
			addCriterion("maxpro <", value, "maxpro");
			return (Criteria) this;
		}

		public Criteria andMaxproLessThanOrEqualTo(String value) {
			addCriterion("maxpro <=", value, "maxpro");
			return (Criteria) this;
		}

		public Criteria andMaxproLike(String value) {
			addCriterion("maxpro like", value, "maxpro");
			return (Criteria) this;
		}

		public Criteria andMaxproNotLike(String value) {
			addCriterion("maxpro not like", value, "maxpro");
			return (Criteria) this;
		}

		public Criteria andMaxproIn(List<String> values) {
			addCriterion("maxpro in", values, "maxpro");
			return (Criteria) this;
		}

		public Criteria andMaxproNotIn(List<String> values) {
			addCriterion("maxpro not in", values, "maxpro");
			return (Criteria) this;
		}

		public Criteria andMaxproBetween(String value1, String value2) {
			addCriterion("maxpro between", value1, value2, "maxpro");
			return (Criteria) this;
		}

		public Criteria andMaxproNotBetween(String value1, String value2) {
			addCriterion("maxpro not between", value1, value2, "maxpro");
			return (Criteria) this;
		}

		public Criteria andTimproIsNull() {
			addCriterion("timpro is null");
			return (Criteria) this;
		}

		public Criteria andTimproIsNotNull() {
			addCriterion("timpro is not null");
			return (Criteria) this;
		}

		public Criteria andTimproEqualTo(String value) {
			addCriterion("timpro =", value, "timpro");
			return (Criteria) this;
		}

		public Criteria andTimproNotEqualTo(String value) {
			addCriterion("timpro <>", value, "timpro");
			return (Criteria) this;
		}

		public Criteria andTimproGreaterThan(String value) {
			addCriterion("timpro >", value, "timpro");
			return (Criteria) this;
		}

		public Criteria andTimproGreaterThanOrEqualTo(String value) {
			addCriterion("timpro >=", value, "timpro");
			return (Criteria) this;
		}

		public Criteria andTimproLessThan(String value) {
			addCriterion("timpro <", value, "timpro");
			return (Criteria) this;
		}

		public Criteria andTimproLessThanOrEqualTo(String value) {
			addCriterion("timpro <=", value, "timpro");
			return (Criteria) this;
		}

		public Criteria andTimproLike(String value) {
			addCriterion("timpro like", value, "timpro");
			return (Criteria) this;
		}

		public Criteria andTimproNotLike(String value) {
			addCriterion("timpro not like", value, "timpro");
			return (Criteria) this;
		}

		public Criteria andTimproIn(List<String> values) {
			addCriterion("timpro in", values, "timpro");
			return (Criteria) this;
		}

		public Criteria andTimproNotIn(List<String> values) {
			addCriterion("timpro not in", values, "timpro");
			return (Criteria) this;
		}

		public Criteria andTimproBetween(String value1, String value2) {
			addCriterion("timpro between", value1, value2, "timpro");
			return (Criteria) this;
		}

		public Criteria andTimproNotBetween(String value1, String value2) {
			addCriterion("timpro not between", value1, value2, "timpro");
			return (Criteria) this;
		}

		public Criteria andDtulproIsNull() {
			addCriterion("dtulpro is null");
			return (Criteria) this;
		}

		public Criteria andDtulproIsNotNull() {
			addCriterion("dtulpro is not null");
			return (Criteria) this;
		}

		public Criteria andDtulproEqualTo(String value) {
			addCriterion("dtulpro =", value, "dtulpro");
			return (Criteria) this;
		}

		public Criteria andDtulproNotEqualTo(String value) {
			addCriterion("dtulpro <>", value, "dtulpro");
			return (Criteria) this;
		}

		public Criteria andDtulproGreaterThan(String value) {
			addCriterion("dtulpro >", value, "dtulpro");
			return (Criteria) this;
		}

		public Criteria andDtulproGreaterThanOrEqualTo(String value) {
			addCriterion("dtulpro >=", value, "dtulpro");
			return (Criteria) this;
		}

		public Criteria andDtulproLessThan(String value) {
			addCriterion("dtulpro <", value, "dtulpro");
			return (Criteria) this;
		}

		public Criteria andDtulproLessThanOrEqualTo(String value) {
			addCriterion("dtulpro <=", value, "dtulpro");
			return (Criteria) this;
		}

		public Criteria andDtulproLike(String value) {
			addCriterion("dtulpro like", value, "dtulpro");
			return (Criteria) this;
		}

		public Criteria andDtulproNotLike(String value) {
			addCriterion("dtulpro not like", value, "dtulpro");
			return (Criteria) this;
		}

		public Criteria andDtulproIn(List<String> values) {
			addCriterion("dtulpro in", values, "dtulpro");
			return (Criteria) this;
		}

		public Criteria andDtulproNotIn(List<String> values) {
			addCriterion("dtulpro not in", values, "dtulpro");
			return (Criteria) this;
		}

		public Criteria andDtulproBetween(String value1, String value2) {
			addCriterion("dtulpro between", value1, value2, "dtulpro");
			return (Criteria) this;
		}

		public Criteria andDtulproNotBetween(String value1, String value2) {
			addCriterion("dtulpro not between", value1, value2, "dtulpro");
			return (Criteria) this;
		}

		public Criteria andDatinsIsNull() {
			addCriterion("datins is null");
			return (Criteria) this;
		}

		public Criteria andDatinsIsNotNull() {
			addCriterion("datins is not null");
			return (Criteria) this;
		}

		public Criteria andDatinsEqualTo(String value) {
			addCriterion("datins =", value, "datins");
			return (Criteria) this;
		}

		public Criteria andDatinsNotEqualTo(String value) {
			addCriterion("datins <>", value, "datins");
			return (Criteria) this;
		}

		public Criteria andDatinsGreaterThan(String value) {
			addCriterion("datins >", value, "datins");
			return (Criteria) this;
		}

		public Criteria andDatinsGreaterThanOrEqualTo(String value) {
			addCriterion("datins >=", value, "datins");
			return (Criteria) this;
		}

		public Criteria andDatinsLessThan(String value) {
			addCriterion("datins <", value, "datins");
			return (Criteria) this;
		}

		public Criteria andDatinsLessThanOrEqualTo(String value) {
			addCriterion("datins <=", value, "datins");
			return (Criteria) this;
		}

		public Criteria andDatinsLike(String value) {
			addCriterion("datins like", value, "datins");
			return (Criteria) this;
		}

		public Criteria andDatinsNotLike(String value) {
			addCriterion("datins not like", value, "datins");
			return (Criteria) this;
		}

		public Criteria andDatinsIn(List<String> values) {
			addCriterion("datins in", values, "datins");
			return (Criteria) this;
		}

		public Criteria andDatinsNotIn(List<String> values) {
			addCriterion("datins not in", values, "datins");
			return (Criteria) this;
		}

		public Criteria andDatinsBetween(String value1, String value2) {
			addCriterion("datins between", value1, value2, "datins");
			return (Criteria) this;
		}

		public Criteria andDatinsNotBetween(String value1, String value2) {
			addCriterion("datins not between", value1, value2, "datins");
			return (Criteria) this;
		}

		public Criteria andLnominIsNull() {
			addCriterion("lnomin is null");
			return (Criteria) this;
		}

		public Criteria andLnominIsNotNull() {
			addCriterion("lnomin is not null");
			return (Criteria) this;
		}

		public Criteria andLnominEqualTo(String value) {
			addCriterion("lnomin =", value, "lnomin");
			return (Criteria) this;
		}

		public Criteria andLnominNotEqualTo(String value) {
			addCriterion("lnomin <>", value, "lnomin");
			return (Criteria) this;
		}

		public Criteria andLnominGreaterThan(String value) {
			addCriterion("lnomin >", value, "lnomin");
			return (Criteria) this;
		}

		public Criteria andLnominGreaterThanOrEqualTo(String value) {
			addCriterion("lnomin >=", value, "lnomin");
			return (Criteria) this;
		}

		public Criteria andLnominLessThan(String value) {
			addCriterion("lnomin <", value, "lnomin");
			return (Criteria) this;
		}

		public Criteria andLnominLessThanOrEqualTo(String value) {
			addCriterion("lnomin <=", value, "lnomin");
			return (Criteria) this;
		}

		public Criteria andLnominLike(String value) {
			addCriterion("lnomin like", value, "lnomin");
			return (Criteria) this;
		}

		public Criteria andLnominNotLike(String value) {
			addCriterion("lnomin not like", value, "lnomin");
			return (Criteria) this;
		}

		public Criteria andLnominIn(List<String> values) {
			addCriterion("lnomin in", values, "lnomin");
			return (Criteria) this;
		}

		public Criteria andLnominNotIn(List<String> values) {
			addCriterion("lnomin not in", values, "lnomin");
			return (Criteria) this;
		}

		public Criteria andLnominBetween(String value1, String value2) {
			addCriterion("lnomin between", value1, value2, "lnomin");
			return (Criteria) this;
		}

		public Criteria andLnominNotBetween(String value1, String value2) {
			addCriterion("lnomin not between", value1, value2, "lnomin");
			return (Criteria) this;
		}

		public Criteria andNominatIsNull() {
			addCriterion("nominat is null");
			return (Criteria) this;
		}

		public Criteria andNominatIsNotNull() {
			addCriterion("nominat is not null");
			return (Criteria) this;
		}

		public Criteria andNominatEqualTo(String value) {
			addCriterion("nominat =", value, "nominat");
			return (Criteria) this;
		}

		public Criteria andNominatNotEqualTo(String value) {
			addCriterion("nominat <>", value, "nominat");
			return (Criteria) this;
		}

		public Criteria andNominatGreaterThan(String value) {
			addCriterion("nominat >", value, "nominat");
			return (Criteria) this;
		}

		public Criteria andNominatGreaterThanOrEqualTo(String value) {
			addCriterion("nominat >=", value, "nominat");
			return (Criteria) this;
		}

		public Criteria andNominatLessThan(String value) {
			addCriterion("nominat <", value, "nominat");
			return (Criteria) this;
		}

		public Criteria andNominatLessThanOrEqualTo(String value) {
			addCriterion("nominat <=", value, "nominat");
			return (Criteria) this;
		}

		public Criteria andNominatLike(String value) {
			addCriterion("nominat like", value, "nominat");
			return (Criteria) this;
		}

		public Criteria andNominatNotLike(String value) {
			addCriterion("nominat not like", value, "nominat");
			return (Criteria) this;
		}

		public Criteria andNominatIn(List<String> values) {
			addCriterion("nominat in", values, "nominat");
			return (Criteria) this;
		}

		public Criteria andNominatNotIn(List<String> values) {
			addCriterion("nominat not in", values, "nominat");
			return (Criteria) this;
		}

		public Criteria andNominatBetween(String value1, String value2) {
			addCriterion("nominat between", value1, value2, "nominat");
			return (Criteria) this;
		}

		public Criteria andNominatNotBetween(String value1, String value2) {
			addCriterion("nominat not between", value1, value2, "nominat");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table saran
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table saran
     *
     * @mbggenerated do_not_delete_during_merge Mon Feb 18 16:23:50 CET 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}