package it.amedeo.mybatis.javamodel;

public class Sarin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarin.tipoparola
	 * @mbggenerated
	 */
	private String tipoparola;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarin.parola
	 * @mbggenerated
	 */
	private String parola;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarin.regione
	 * @mbggenerated
	 */
	private String regione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarin.ricorrenze
	 * @mbggenerated
	 */
	private Integer ricorrenze;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarin.puntapr
	 * @mbggenerated
	 */
	private Integer puntapr;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarin.tipoparola
	 * @return  the value of sarin.tipoparola
	 * @mbggenerated
	 */
	public String getTipoparola() {
		return tipoparola;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarin.tipoparola
	 * @param tipoparola  the value for sarin.tipoparola
	 * @mbggenerated
	 */
	public void setTipoparola(String tipoparola) {
		this.tipoparola = tipoparola;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarin.parola
	 * @return  the value of sarin.parola
	 * @mbggenerated
	 */
	public String getParola() {
		return parola;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarin.parola
	 * @param parola  the value for sarin.parola
	 * @mbggenerated
	 */
	public void setParola(String parola) {
		this.parola = parola;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarin.regione
	 * @return  the value of sarin.regione
	 * @mbggenerated
	 */
	public String getRegione() {
		return regione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarin.regione
	 * @param regione  the value for sarin.regione
	 * @mbggenerated
	 */
	public void setRegione(String regione) {
		this.regione = regione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarin.ricorrenze
	 * @return  the value of sarin.ricorrenze
	 * @mbggenerated
	 */
	public Integer getRicorrenze() {
		return ricorrenze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarin.ricorrenze
	 * @param ricorrenze  the value for sarin.ricorrenze
	 * @mbggenerated
	 */
	public void setRicorrenze(Integer ricorrenze) {
		this.ricorrenze = ricorrenze;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarin.puntapr
	 * @return  the value of sarin.puntapr
	 * @mbggenerated
	 */
	public Integer getPuntapr() {
		return puntapr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarin.puntapr
	 * @param puntapr  the value for sarin.puntapr
	 * @mbggenerated
	 */
	public void setPuntapr(Integer puntapr) {
		this.puntapr = puntapr;
	}
}