package it.amedeo.mybatis.javamodel;

public class Sarpr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarpr.progressivi
	 * @mbggenerated
	 */
	private String progressivi;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarpr.progressivi
	 * @return  the value of sarpr.progressivi
	 * @mbggenerated
	 */
	public String getProgressivi() {
		return progressivi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarpr.progressivi
	 * @param progressivi  the value for sarpr.progressivi
	 * @mbggenerated
	 */
	public void setProgressivi(String progressivi) {
		this.progressivi = progressivi;
	}
}