package it.amedeo.mybatis.javamodel;

public class Sarsyc {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarsyc.regione
	 * @mbggenerated
	 */
	private String regione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarsyc.istat
	 * @mbggenerated
	 */
	private String istat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarsyc.progrmin
	 * @mbggenerated
	 */
	private String progrmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarsyc.progrmax
	 * @mbggenerated
	 */
	private String progrmax;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarsyc.regione
	 * @return  the value of sarsyc.regione
	 * @mbggenerated
	 */
	public String getRegione() {
		return regione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarsyc.regione
	 * @param regione  the value for sarsyc.regione
	 * @mbggenerated
	 */
	public void setRegione(String regione) {
		this.regione = regione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarsyc.istat
	 * @return  the value of sarsyc.istat
	 * @mbggenerated
	 */
	public String getIstat() {
		return istat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarsyc.istat
	 * @param istat  the value for sarsyc.istat
	 * @mbggenerated
	 */
	public void setIstat(String istat) {
		this.istat = istat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarsyc.progrmin
	 * @return  the value of sarsyc.progrmin
	 * @mbggenerated
	 */
	public String getProgrmin() {
		return progrmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarsyc.progrmin
	 * @param progrmin  the value for sarsyc.progrmin
	 * @mbggenerated
	 */
	public void setProgrmin(String progrmin) {
		this.progrmin = progrmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarsyc.progrmax
	 * @return  the value of sarsyc.progrmax
	 * @mbggenerated
	 */
	public String getProgrmax() {
		return progrmax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarsyc.progrmax
	 * @param progrmax  the value for sarsyc.progrmax
	 * @mbggenerated
	 */
	public void setProgrmax(String progrmax) {
		this.progrmax = progrmax;
	}
}