package it.amedeo.mybatis.javamodel;

public class Sarsya {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarsya.codistatprv
	 * @mbggenerated
	 */
	private String codistatprv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarsya.datiscmin
	 * @mbggenerated
	 */
	private String datiscmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarsya.datiscmax
	 * @mbggenerated
	 */
	private String datiscmax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarsya.datlevmin
	 * @mbggenerated
	 */
	private String datlevmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarsya.datlevmax
	 * @mbggenerated
	 */
	private String datlevmax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarsya.totana
	 * @mbggenerated
	 */
	private Integer totana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sarsya.toteff
	 * @mbggenerated
	 */
	private Integer toteff;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarsya.codistatprv
	 * @return  the value of sarsya.codistatprv
	 * @mbggenerated
	 */
	public String getCodistatprv() {
		return codistatprv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarsya.codistatprv
	 * @param codistatprv  the value for sarsya.codistatprv
	 * @mbggenerated
	 */
	public void setCodistatprv(String codistatprv) {
		this.codistatprv = codistatprv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarsya.datiscmin
	 * @return  the value of sarsya.datiscmin
	 * @mbggenerated
	 */
	public String getDatiscmin() {
		return datiscmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarsya.datiscmin
	 * @param datiscmin  the value for sarsya.datiscmin
	 * @mbggenerated
	 */
	public void setDatiscmin(String datiscmin) {
		this.datiscmin = datiscmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarsya.datiscmax
	 * @return  the value of sarsya.datiscmax
	 * @mbggenerated
	 */
	public String getDatiscmax() {
		return datiscmax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarsya.datiscmax
	 * @param datiscmax  the value for sarsya.datiscmax
	 * @mbggenerated
	 */
	public void setDatiscmax(String datiscmax) {
		this.datiscmax = datiscmax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarsya.datlevmin
	 * @return  the value of sarsya.datlevmin
	 * @mbggenerated
	 */
	public String getDatlevmin() {
		return datlevmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarsya.datlevmin
	 * @param datlevmin  the value for sarsya.datlevmin
	 * @mbggenerated
	 */
	public void setDatlevmin(String datlevmin) {
		this.datlevmin = datlevmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarsya.datlevmax
	 * @return  the value of sarsya.datlevmax
	 * @mbggenerated
	 */
	public String getDatlevmax() {
		return datlevmax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarsya.datlevmax
	 * @param datlevmax  the value for sarsya.datlevmax
	 * @mbggenerated
	 */
	public void setDatlevmax(String datlevmax) {
		this.datlevmax = datlevmax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarsya.totana
	 * @return  the value of sarsya.totana
	 * @mbggenerated
	 */
	public Integer getTotana() {
		return totana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarsya.totana
	 * @param totana  the value for sarsya.totana
	 * @mbggenerated
	 */
	public void setTotana(Integer totana) {
		this.totana = totana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sarsya.toteff
	 * @return  the value of sarsya.toteff
	 * @mbggenerated
	 */
	public Integer getToteff() {
		return toteff;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sarsya.toteff
	 * @param toteff  the value for sarsya.toteff
	 * @mbggenerated
	 */
	public void setToteff(Integer toteff) {
		this.toteff = toteff;
	}
}