package it.amedeo.mybatis.javamodel;

import java.util.ArrayList;
import java.util.List;

public class SarsyaExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sarsya
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sarsya
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sarsya
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	public SarsyaExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sarsya
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodistatprvIsNull() {
			addCriterion("codistatprv is null");
			return (Criteria) this;
		}

		public Criteria andCodistatprvIsNotNull() {
			addCriterion("codistatprv is not null");
			return (Criteria) this;
		}

		public Criteria andCodistatprvEqualTo(String value) {
			addCriterion("codistatprv =", value, "codistatprv");
			return (Criteria) this;
		}

		public Criteria andCodistatprvNotEqualTo(String value) {
			addCriterion("codistatprv <>", value, "codistatprv");
			return (Criteria) this;
		}

		public Criteria andCodistatprvGreaterThan(String value) {
			addCriterion("codistatprv >", value, "codistatprv");
			return (Criteria) this;
		}

		public Criteria andCodistatprvGreaterThanOrEqualTo(String value) {
			addCriterion("codistatprv >=", value, "codistatprv");
			return (Criteria) this;
		}

		public Criteria andCodistatprvLessThan(String value) {
			addCriterion("codistatprv <", value, "codistatprv");
			return (Criteria) this;
		}

		public Criteria andCodistatprvLessThanOrEqualTo(String value) {
			addCriterion("codistatprv <=", value, "codistatprv");
			return (Criteria) this;
		}

		public Criteria andCodistatprvLike(String value) {
			addCriterion("codistatprv like", value, "codistatprv");
			return (Criteria) this;
		}

		public Criteria andCodistatprvNotLike(String value) {
			addCriterion("codistatprv not like", value, "codistatprv");
			return (Criteria) this;
		}

		public Criteria andCodistatprvIn(List<String> values) {
			addCriterion("codistatprv in", values, "codistatprv");
			return (Criteria) this;
		}

		public Criteria andCodistatprvNotIn(List<String> values) {
			addCriterion("codistatprv not in", values, "codistatprv");
			return (Criteria) this;
		}

		public Criteria andCodistatprvBetween(String value1, String value2) {
			addCriterion("codistatprv between", value1, value2, "codistatprv");
			return (Criteria) this;
		}

		public Criteria andCodistatprvNotBetween(String value1, String value2) {
			addCriterion("codistatprv not between", value1, value2, "codistatprv");
			return (Criteria) this;
		}

		public Criteria andDatiscminIsNull() {
			addCriterion("datiscmin is null");
			return (Criteria) this;
		}

		public Criteria andDatiscminIsNotNull() {
			addCriterion("datiscmin is not null");
			return (Criteria) this;
		}

		public Criteria andDatiscminEqualTo(String value) {
			addCriterion("datiscmin =", value, "datiscmin");
			return (Criteria) this;
		}

		public Criteria andDatiscminNotEqualTo(String value) {
			addCriterion("datiscmin <>", value, "datiscmin");
			return (Criteria) this;
		}

		public Criteria andDatiscminGreaterThan(String value) {
			addCriterion("datiscmin >", value, "datiscmin");
			return (Criteria) this;
		}

		public Criteria andDatiscminGreaterThanOrEqualTo(String value) {
			addCriterion("datiscmin >=", value, "datiscmin");
			return (Criteria) this;
		}

		public Criteria andDatiscminLessThan(String value) {
			addCriterion("datiscmin <", value, "datiscmin");
			return (Criteria) this;
		}

		public Criteria andDatiscminLessThanOrEqualTo(String value) {
			addCriterion("datiscmin <=", value, "datiscmin");
			return (Criteria) this;
		}

		public Criteria andDatiscminLike(String value) {
			addCriterion("datiscmin like", value, "datiscmin");
			return (Criteria) this;
		}

		public Criteria andDatiscminNotLike(String value) {
			addCriterion("datiscmin not like", value, "datiscmin");
			return (Criteria) this;
		}

		public Criteria andDatiscminIn(List<String> values) {
			addCriterion("datiscmin in", values, "datiscmin");
			return (Criteria) this;
		}

		public Criteria andDatiscminNotIn(List<String> values) {
			addCriterion("datiscmin not in", values, "datiscmin");
			return (Criteria) this;
		}

		public Criteria andDatiscminBetween(String value1, String value2) {
			addCriterion("datiscmin between", value1, value2, "datiscmin");
			return (Criteria) this;
		}

		public Criteria andDatiscminNotBetween(String value1, String value2) {
			addCriterion("datiscmin not between", value1, value2, "datiscmin");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxIsNull() {
			addCriterion("datiscmax is null");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxIsNotNull() {
			addCriterion("datiscmax is not null");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxEqualTo(String value) {
			addCriterion("datiscmax =", value, "datiscmax");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxNotEqualTo(String value) {
			addCriterion("datiscmax <>", value, "datiscmax");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxGreaterThan(String value) {
			addCriterion("datiscmax >", value, "datiscmax");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxGreaterThanOrEqualTo(String value) {
			addCriterion("datiscmax >=", value, "datiscmax");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxLessThan(String value) {
			addCriterion("datiscmax <", value, "datiscmax");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxLessThanOrEqualTo(String value) {
			addCriterion("datiscmax <=", value, "datiscmax");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxLike(String value) {
			addCriterion("datiscmax like", value, "datiscmax");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxNotLike(String value) {
			addCriterion("datiscmax not like", value, "datiscmax");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxIn(List<String> values) {
			addCriterion("datiscmax in", values, "datiscmax");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxNotIn(List<String> values) {
			addCriterion("datiscmax not in", values, "datiscmax");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxBetween(String value1, String value2) {
			addCriterion("datiscmax between", value1, value2, "datiscmax");
			return (Criteria) this;
		}

		public Criteria andDatiscmaxNotBetween(String value1, String value2) {
			addCriterion("datiscmax not between", value1, value2, "datiscmax");
			return (Criteria) this;
		}

		public Criteria andDatlevminIsNull() {
			addCriterion("datlevmin is null");
			return (Criteria) this;
		}

		public Criteria andDatlevminIsNotNull() {
			addCriterion("datlevmin is not null");
			return (Criteria) this;
		}

		public Criteria andDatlevminEqualTo(String value) {
			addCriterion("datlevmin =", value, "datlevmin");
			return (Criteria) this;
		}

		public Criteria andDatlevminNotEqualTo(String value) {
			addCriterion("datlevmin <>", value, "datlevmin");
			return (Criteria) this;
		}

		public Criteria andDatlevminGreaterThan(String value) {
			addCriterion("datlevmin >", value, "datlevmin");
			return (Criteria) this;
		}

		public Criteria andDatlevminGreaterThanOrEqualTo(String value) {
			addCriterion("datlevmin >=", value, "datlevmin");
			return (Criteria) this;
		}

		public Criteria andDatlevminLessThan(String value) {
			addCriterion("datlevmin <", value, "datlevmin");
			return (Criteria) this;
		}

		public Criteria andDatlevminLessThanOrEqualTo(String value) {
			addCriterion("datlevmin <=", value, "datlevmin");
			return (Criteria) this;
		}

		public Criteria andDatlevminLike(String value) {
			addCriterion("datlevmin like", value, "datlevmin");
			return (Criteria) this;
		}

		public Criteria andDatlevminNotLike(String value) {
			addCriterion("datlevmin not like", value, "datlevmin");
			return (Criteria) this;
		}

		public Criteria andDatlevminIn(List<String> values) {
			addCriterion("datlevmin in", values, "datlevmin");
			return (Criteria) this;
		}

		public Criteria andDatlevminNotIn(List<String> values) {
			addCriterion("datlevmin not in", values, "datlevmin");
			return (Criteria) this;
		}

		public Criteria andDatlevminBetween(String value1, String value2) {
			addCriterion("datlevmin between", value1, value2, "datlevmin");
			return (Criteria) this;
		}

		public Criteria andDatlevminNotBetween(String value1, String value2) {
			addCriterion("datlevmin not between", value1, value2, "datlevmin");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxIsNull() {
			addCriterion("datlevmax is null");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxIsNotNull() {
			addCriterion("datlevmax is not null");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxEqualTo(String value) {
			addCriterion("datlevmax =", value, "datlevmax");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxNotEqualTo(String value) {
			addCriterion("datlevmax <>", value, "datlevmax");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxGreaterThan(String value) {
			addCriterion("datlevmax >", value, "datlevmax");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxGreaterThanOrEqualTo(String value) {
			addCriterion("datlevmax >=", value, "datlevmax");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxLessThan(String value) {
			addCriterion("datlevmax <", value, "datlevmax");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxLessThanOrEqualTo(String value) {
			addCriterion("datlevmax <=", value, "datlevmax");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxLike(String value) {
			addCriterion("datlevmax like", value, "datlevmax");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxNotLike(String value) {
			addCriterion("datlevmax not like", value, "datlevmax");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxIn(List<String> values) {
			addCriterion("datlevmax in", values, "datlevmax");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxNotIn(List<String> values) {
			addCriterion("datlevmax not in", values, "datlevmax");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxBetween(String value1, String value2) {
			addCriterion("datlevmax between", value1, value2, "datlevmax");
			return (Criteria) this;
		}

		public Criteria andDatlevmaxNotBetween(String value1, String value2) {
			addCriterion("datlevmax not between", value1, value2, "datlevmax");
			return (Criteria) this;
		}

		public Criteria andTotanaIsNull() {
			addCriterion("totana is null");
			return (Criteria) this;
		}

		public Criteria andTotanaIsNotNull() {
			addCriterion("totana is not null");
			return (Criteria) this;
		}

		public Criteria andTotanaEqualTo(Integer value) {
			addCriterion("totana =", value, "totana");
			return (Criteria) this;
		}

		public Criteria andTotanaNotEqualTo(Integer value) {
			addCriterion("totana <>", value, "totana");
			return (Criteria) this;
		}

		public Criteria andTotanaGreaterThan(Integer value) {
			addCriterion("totana >", value, "totana");
			return (Criteria) this;
		}

		public Criteria andTotanaGreaterThanOrEqualTo(Integer value) {
			addCriterion("totana >=", value, "totana");
			return (Criteria) this;
		}

		public Criteria andTotanaLessThan(Integer value) {
			addCriterion("totana <", value, "totana");
			return (Criteria) this;
		}

		public Criteria andTotanaLessThanOrEqualTo(Integer value) {
			addCriterion("totana <=", value, "totana");
			return (Criteria) this;
		}

		public Criteria andTotanaIn(List<Integer> values) {
			addCriterion("totana in", values, "totana");
			return (Criteria) this;
		}

		public Criteria andTotanaNotIn(List<Integer> values) {
			addCriterion("totana not in", values, "totana");
			return (Criteria) this;
		}

		public Criteria andTotanaBetween(Integer value1, Integer value2) {
			addCriterion("totana between", value1, value2, "totana");
			return (Criteria) this;
		}

		public Criteria andTotanaNotBetween(Integer value1, Integer value2) {
			addCriterion("totana not between", value1, value2, "totana");
			return (Criteria) this;
		}

		public Criteria andToteffIsNull() {
			addCriterion("toteff is null");
			return (Criteria) this;
		}

		public Criteria andToteffIsNotNull() {
			addCriterion("toteff is not null");
			return (Criteria) this;
		}

		public Criteria andToteffEqualTo(Integer value) {
			addCriterion("toteff =", value, "toteff");
			return (Criteria) this;
		}

		public Criteria andToteffNotEqualTo(Integer value) {
			addCriterion("toteff <>", value, "toteff");
			return (Criteria) this;
		}

		public Criteria andToteffGreaterThan(Integer value) {
			addCriterion("toteff >", value, "toteff");
			return (Criteria) this;
		}

		public Criteria andToteffGreaterThanOrEqualTo(Integer value) {
			addCriterion("toteff >=", value, "toteff");
			return (Criteria) this;
		}

		public Criteria andToteffLessThan(Integer value) {
			addCriterion("toteff <", value, "toteff");
			return (Criteria) this;
		}

		public Criteria andToteffLessThanOrEqualTo(Integer value) {
			addCriterion("toteff <=", value, "toteff");
			return (Criteria) this;
		}

		public Criteria andToteffIn(List<Integer> values) {
			addCriterion("toteff in", values, "toteff");
			return (Criteria) this;
		}

		public Criteria andToteffNotIn(List<Integer> values) {
			addCriterion("toteff not in", values, "toteff");
			return (Criteria) this;
		}

		public Criteria andToteffBetween(Integer value1, Integer value2) {
			addCriterion("toteff between", value1, value2, "toteff");
			return (Criteria) this;
		}

		public Criteria andToteffNotBetween(Integer value1, Integer value2) {
			addCriterion("toteff not between", value1, value2, "toteff");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sarsya
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sarsya
     *
     * @mbggenerated do_not_delete_during_merge Mon Feb 18 16:23:50 CET 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}