package it.amedeo.mybatis.javaclient;

import it.amedeo.mybatis.javamodel.Regprv;
import it.amedeo.mybatis.javamodel.RegprvExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegprvMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	int countByExample(RegprvExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	int deleteByExample(RegprvExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	int insert(Regprv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	int insertSelective(Regprv record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	List<Regprv> selectByExample(RegprvExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Regprv record, @Param("example") RegprvExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regprv
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Regprv record, @Param("example") RegprvExample example);
}