package it.amedeo.mybatis.javaclient;

import it.amedeo.mybatis.javamodel.Saran;
import it.amedeo.mybatis.javamodel.SaranExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaranMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	int countByExample(SaranExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	int deleteByExample(SaranExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	int insert(Saran record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	int insertSelective(Saran record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	List<Saran> selectByExample(SaranExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Saran record, @Param("example") SaranExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table saran
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Saran record, @Param("example") SaranExample example);
}