package it.amedeo.mybatis.javaclient;

import it.amedeo.mybatis.javamodel.Sarap;
import it.amedeo.mybatis.javamodel.SarapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SarapMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	int countByExample(SarapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	int deleteByExample(SarapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	int insert(Sarap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	int insertSelective(Sarap record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	List<Sarap> selectByExample(SarapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Sarap record, @Param("example") SarapExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarap
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Sarap record, @Param("example") SarapExample example);
}