package it.amedeo.mybatis.javaclient;

import it.amedeo.mybatis.javamodel.Sarin;
import it.amedeo.mybatis.javamodel.SarinExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SarinMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarin
	 * @mbggenerated
	 */
	int countByExample(SarinExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarin
	 * @mbggenerated
	 */
	int deleteByExample(SarinExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarin
	 * @mbggenerated
	 */
	int insert(Sarin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarin
	 * @mbggenerated
	 */
	int insertSelective(Sarin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarin
	 * @mbggenerated
	 */
	List<Sarin> selectByExample(SarinExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarin
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Sarin record, @Param("example") SarinExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarin
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Sarin record, @Param("example") SarinExample example);
}