package it.amedeo.mybatis.javaclient;

import it.amedeo.mybatis.javamodel.Sarpr;
import it.amedeo.mybatis.javamodel.SarprExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SarprMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarpr
	 * @mbggenerated
	 */
	int countByExample(SarprExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarpr
	 * @mbggenerated
	 */
	int deleteByExample(SarprExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarpr
	 * @mbggenerated
	 */
	int insert(Sarpr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarpr
	 * @mbggenerated
	 */
	int insertSelective(Sarpr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarpr
	 * @mbggenerated
	 */
	List<Sarpr> selectByExample(SarprExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarpr
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Sarpr record, @Param("example") SarprExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarpr
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Sarpr record, @Param("example") SarprExample example);
}