package it.amedeo.mybatis.javaclient;

import it.amedeo.mybatis.javamodel.Sarsya;
import it.amedeo.mybatis.javamodel.SarsyaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SarsyaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	int countByExample(SarsyaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	int deleteByExample(SarsyaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String codistatprv);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	int insert(Sarsya record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	int insertSelective(Sarsya record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	List<Sarsya> selectByExample(SarsyaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	Sarsya selectByPrimaryKey(String codistatprv);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Sarsya record, @Param("example") SarsyaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Sarsya record, @Param("example") SarsyaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Sarsya record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsya
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Sarsya record);
}