package it.amedeo.mybatis.javaclient;

import it.amedeo.mybatis.javamodel.Sarsyc;
import it.amedeo.mybatis.javamodel.SarsycExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SarsycMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsyc
	 * @mbggenerated
	 */
	int countByExample(SarsycExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsyc
	 * @mbggenerated
	 */
	int deleteByExample(SarsycExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsyc
	 * @mbggenerated
	 */
	int insert(Sarsyc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsyc
	 * @mbggenerated
	 */
	int insertSelective(Sarsyc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsyc
	 * @mbggenerated
	 */
	List<Sarsyc> selectByExample(SarsycExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsyc
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Sarsyc record, @Param("example") SarsycExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sarsyc
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Sarsyc record, @Param("example") SarsycExample example);
}