package it.amedeo.mybatis.javaclient;

import it.amedeo.mybatis.javamodel.Strdatnas;
import it.amedeo.mybatis.javamodel.StrdatnasExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import it.amedeo.mybatis.javamodel.StrdatnasKey;

public interface StrdatnasMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strdatnas
	 * @mbggenerated
	 */
	int countByExample(StrdatnasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strdatnas
	 * @mbggenerated
	 */
	int deleteByExample(StrdatnasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strdatnas
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(StrdatnasKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strdatnas
	 * @mbggenerated
	 */
	int insert(Strdatnas record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strdatnas
	 * @mbggenerated
	 */
	int insertSelective(Strdatnas record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strdatnas
	 * @mbggenerated
	 */
	List<Strdatnas> selectByExample(StrdatnasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strdatnas
	 * @mbggenerated
	 */
	Strdatnas selectByPrimaryKey(StrdatnasKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strdatnas
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Strdatnas record, @Param("example") StrdatnasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strdatnas
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Strdatnas record, @Param("example") StrdatnasExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strdatnas
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Strdatnas record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table strdatnas
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Strdatnas record);
}